import type { Landmark } from "../schema";

/**
 * Everything the landmark scanner can identify inside Magdalen College's
 * grounds. Coordinates come from OpenStreetMap building/tree/path data
 * (surveyed by mappers, but still only accurate to a few metres); facts come
 * from the college's own website and catalogue, the National Gardens Scheme,
 * Historic England and Wikipedia. Aliases starting with "~" are generic
 * image labels ("tower", "tree") that only weakly suggest a landmark — GPS
 * position and compass heading decide between the candidates.
 *
 * The narrator says "Maudlin" (the real Oxford pronunciation), so audio
 * prompts spell it that way — see scripts in assets/audio/oxford-magdalen.
 */
export const magdalenLandmarks: Landmark[] = [
  {
    id: "great-tower",
    name: "Magdalen Tower",
    category: "building",
    aliases: ["magdalen tower", "great tower", "magdalen college tower", "~bell tower", "~tower", "~belfry", "~steeple", "~spire"],
    coordinates: { lat: 51.751722, lng: -1.246862 },
    radiusMeters: 90,
    spokenText: `This is the Great Tower, Magdalen's most famous landmark. It stands a hundred and forty-four feet tall, and building began in 1492, when Dr Richard Mayew laid the foundation stone on the ninth of August. It was finished in 1509 under the master mason William Raynold. Ten bells hang inside, the heaviest cast in 1623. And every first of May at six in the morning, the college choir sings from the very top — which is why crowds gather on the High Street below before dawn.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/great-tower.mp3"),
  },
  {
    id: "chapel",
    name: "Magdalen College Chapel",
    category: "building",
    aliases: ["magdalen college chapel", "magdalen chapel", "college chapel", "~chapel", "~church", "~gothic architecture", "~medieval architecture"],
    coordinates: { lat: 51.751981, lng: -1.246959 },
    radiusMeters: 40,
    spokenText: `This is the college chapel, built between 1474 and 1480 when the college was new. It has been the heart of Magdalen's life ever since, and the choir is world-famous — it sings a service at six most evenings in term, and everyone is welcome to attend, even outside the college's visiting hours. Inside, look for the great carved stone screen behind the altar, and the plaster ceiling that was designed to imitate stone vaulting.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/chapel.mp3"),
  },
  {
    id: "chapel-interior",
    name: "The Chapel's screen, ceiling and window",
    category: "building",
    aliases: ["reredos", "altar screen", "stained glass", "~stained glass window", "~altar", "~ceiling", "~vault", "~interior"],
    coordinates: { lat: 51.751981, lng: -1.246959 },
    radiusMeters: 20,
    spokenText: `Three things to look at inside the chapel. The stone screen behind the altar is a reredos, designed by Lewis Cottingham in the 1830s, with three tiers of thirteen niches — the figures that fill them were carved by Thomas Earp in 1864 and 1865. The ceiling looks like stone vaulting, but it's plaster, put up by the architect James Wyatt in 1790. And the window by Francis Eginton, dating from 1792, shows the Last Judgement in shades of grey rather than colour.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/chapel-interior.mp3"),
  },
  {
    id: "cloister",
    name: "The Cloister (Great Quad)",
    category: "building",
    aliases: ["cloister", "cloisters", "great quad", "magdalen cloister", "~quadrangle", "~courtyard", "~arcade", "~arch", "~lawn"],
    coordinates: { lat: 51.752139, lng: -1.246496 },
    radiusMeters: 40,
    spokenText: `You're looking at the Cloister, sometimes called the Great Quad, built between 1474 and 1480 by the mason William Orchard. It is the classic picture of medieval Oxford — a covered stone walkway around a square of lawn. One curious fact: the whole north side was pulled down in 1822, on the grounds that it was in disrepair, and rebuilt soon afterwards. As always in the college, please keep to the paths and off the grass.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/cloister.mp3"),
  },
  {
    id: "cloister-grotesques",
    name: "The Cloister's carved figures",
    category: "feature",
    aliases: ["grotesque", "grotesques", "gargoyle", "gargoyles", "~statue", "~sculpture", "~carving", "~stone carving", "~relief"],
    coordinates: { lat: 51.752139, lng: -1.246496 },
    radiusMeters: 25,
    spokenText: `Look up along the Cloister and you'll see small carved figures perched on the stonework. They date from 1508 and are nicknamed the hieroglyphics — each one stands for a virtue or a vice. There's a lion for courage, a pelican for affection, a manticore for pride, a pair of boxers for contention, and a lamia for lust. The fun is in picking out which is which.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/cloister-grotesques.mp3"),
  },
  {
    id: "founders-tower",
    name: "Founder's Tower",
    category: "building",
    aliases: ["founder's tower", "founders tower", "muniment tower", "~tower", "~turret", "~pinnacle", "~gatehouse"],
    coordinates: { lat: 51.752222, lng: -1.24679 },
    radiusMeters: 30,
    spokenText: `This is Founder's Tower, also known as the Muniment Tower. It's richly decorated, with carvings, pinnacles and carved bosses on its vault, and it forms the passage between St John's Quad, where you came in, and the Cloister ahead. It's named for William Waynflete, Bishop of Winchester and Lord Chancellor of England, who founded the college in 1458.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/founders-tower.mp3"),
  },
  {
    id: "st-johns-quad",
    name: "St John's Quad",
    category: "building",
    aliases: ["st john's quad", "saint john's quad", "st johns quad", "first quad", "~quadrangle", "~courtyard", "~cobblestone", "~pavement"],
    coordinates: { lat: 51.752209, lng: -1.247183 },
    radiusMeters: 30,
    spokenText: `This irregular, cobbled space is St John's Quad, the first courtyard inside the main gate. It takes its name from the Hospital of St John the Baptist, which stood on this site before the college was founded in 1458 — the hospital was dissolved the year before. The old Grammar Hall stands beside it, and there is an outdoor stone pulpit here too.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/st-johns-quad.mp3"),
  },
  {
    id: "outdoor-pulpit",
    name: "The Outdoor Pulpit",
    category: "feature",
    aliases: ["pulpit", "outdoor pulpit", "stone pulpit", "~lectern"],
    coordinates: { lat: 51.752209, lng: -1.247183 },
    radiusMeters: 20,
    spokenText: `That stone pulpit in St John's Quad is one of Oxford's rarest sights: a pulpit built to be used outdoors. By tradition, a sermon is preached from it in the open air around the feast of St John the Baptist in June — a custom that echoes the hospital that once stood here.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/outdoor-pulpit.mp3"),
  },
  {
    id: "grammar-hall",
    name: "The Grammar Hall",
    category: "building",
    aliases: ["grammar hall", "old grammar hall", "~stone building", "~medieval building", "~window"],
    coordinates: { lat: 51.752438, lng: -1.247258 },
    radiusMeters: 25,
    spokenText: `This is the old Grammar Hall, beside St John's Quad. It recalls the grammar school that William Waynflete founded alongside his college — Magdalen College School, which began in 1480 and still exists today, just across the river.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/grammar-hall.mp3"),
  },
  {
    id: "porters-lodge",
    name: "The Porters' Lodge and main gate",
    category: "building",
    aliases: ["porters' lodge", "porter's lodge", "porters lodge", "main gate", "college gate", "magdalen college", "~gate", "~gatehouse", "~entrance", "~high street"],
    coordinates: { lat: 51.751981, lng: -1.247348 },
    radiusMeters: 35,
    spokenText: `This is the Porters' Lodge, the main gate onto the High Street. The college is spelled M-A-G-D-A-L-E-N, but it's pronounced Maudlin — a classic Oxford quirk. It was founded in 1458 by William Waynflete, and among its famous members are Oscar Wilde, C. S. Lewis, who was a fellow here for nearly thirty years, and the poet Seamus Heaney.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/porters-lodge.mp3"),
  },
  {
    id: "chaplains-quad",
    name: "Chaplain's Quad",
    category: "building",
    aliases: ["chaplain's quad", "chaplains quad", "~quadrangle", "~courtyard", "~cobblestone"],
    coordinates: { lat: 51.75182, lng: -1.246882 },
    radiusMeters: 30,
    spokenText: `This is Chaplain's Quad, an oddly triangular courtyard running along the side of the Chapel and the Hall down to the Great Tower. That roughly triangular shape was formed once the tower was completed in 1509.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/chaplains-quad.mp3"),
  },
  {
    id: "hall",
    name: "The Hall",
    category: "building",
    aliases: ["magdalen hall", "college hall", "dining hall", "great hall", "~hall", "~dining room", "~window"],
    coordinates: { lat: 51.751825, lng: -1.246468 },
    radiusMeters: 30,
    spokenText: `This is the Hall, where the college's students and fellows dine. It's one of the main areas open to visitors, though it can close around lunchtime when it's needed for meals, so if the door is shut, that's why.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/hall.mp3"),
  },
  {
    id: "old-kitchen-bar",
    name: "The Old Kitchen Bar",
    category: "building",
    aliases: ["old kitchen bar", "old kitchen", "okb", "~bar", "~pub"],
    coordinates: { lat: 51.75182, lng: -1.246071 },
    radiusMeters: 25,
    spokenText: `The Old Kitchen Bar sits in what were once the kitchens of the Hospital of St John the Baptist, the medieval hospital whose site the college took over. Today it's the college bar, and it's one of the areas open to visitors.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/old-kitchen-bar.mp3"),
  },
  {
    id: "new-building",
    name: "The New Building",
    category: "building",
    aliases: ["new building", "magdalen new building", "~colonnade", "~palladian architecture", "~georgian architecture", "~neoclassical architecture", "~stone building", "~columns"],
    coordinates: { lat: 51.752977, lng: -1.245918 },
    radiusMeters: 70,
    spokenText: `This long, classical building is the New Building, and it's nearly three hundred years old — building began in 1733 from designs by Edward Holdsworth. It was meant to be one side of a grand new quadrangle in the Palladian style, with a colonnade along the front, but the rest was never built, and the ends were tidied up in 1824 by Thomas Harrison. Today it houses students and fellows, and the college's wine cellar.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/new-building.mp3"),
  },
  {
    id: "st-swithuns",
    name: "St Swithun's Quad and Tower",
    category: "building",
    aliases: ["st swithun's", "saint swithun's", "st swithuns quad", "~gothic revival architecture", "~tower", "~brick building"],
    coordinates: { lat: 51.7523, lng: -1.247429 },
    radiusMeters: 45,
    spokenText: `St Swithun's Quad is a Victorian Gothic addition, designed between 1880 and 1884 by George Frederick Bodley and Thomas Garner. It stands on the site of the old Magdalen Hall, which moved out in 1822 and later became Hertford College. Enjoy it from wherever you can see it, and follow the college's signs about where visitors may go.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/st-swithuns.mp3"),
  },
  {
    id: "longwall-quad",
    name: "Longwall Quad and Library",
    category: "building",
    aliases: ["longwall quad", "longwall library", "longwall", "~library", "~modern architecture"],
    coordinates: { lat: 51.752781, lng: -1.248219 },
    radiusMeters: 50,
    spokenText: `Longwall Quad was created in 1928 by the architect Giles Gilbert Scott, and it holds the college's Longwall Library. It isn't open to the general public — the college only lets people in on its guided summer tours — so this one is best appreciated from outside.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/longwall-quad.mp3"),
    notOpenToVisitors: true,
  },
  {
    id: "presidents-lodgings",
    name: "The President's Lodgings",
    category: "building",
    aliases: ["president's lodgings", "presidents lodgings", "president's garden", "~walled garden", "~house"],
    coordinates: { lat: 51.752444, lng: -1.246903 },
    radiusMeters: 35,
    spokenText: `Those are the President's Lodgings, the private home of the head of the college, and beside it is the walled President's Garden. Both are private, so please don't wander in — but you can admire them from where you stand.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/presidents-lodgings.mp3"),
    notOpenToVisitors: true,
  },
  {
    id: "christ-and-mary-magdalen",
    name: "Christ and Mary Magdalen statue",
    category: "feature",
    aliases: ["christ and mary magdalen", "noli me tangere", "bronze statue", "~statue", "~sculpture", "~bronze", "~monument"],
    coordinates: { lat: 51.751833, lng: -1.246721 },
    radiusMeters: 20,
    spokenText: `This bronze is by the sculptor David Wynne, and it shows the risen Christ and Mary Magdalene — the saint the college is named after. It's a moving piece to find in a courtyard of such old stone.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/christ-and-mary-magdalen.mp3"),
  },
  {
    id: "holywell-ford",
    name: "Holywell Ford",
    category: "building",
    aliases: ["holywell ford", "holywell ford house", "~house", "~gate", "~garden gate"],
    coordinates: { lat: 51.754883, lng: -1.245373 },
    radiusMeters: 50,
    spokenText: `Holywell Ford is a group of college buildings at the north-eastern corner of the grounds, right beside Addison's Walk. Near the gate there's a plaque commemorating a poem that C. S. Lewis wrote about this very walk.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/holywell-ford.mp3"),
  },
  {
    id: "magdalen-bridge",
    name: "Magdalen Bridge",
    category: "building",
    aliases: ["magdalen bridge", "~bridge", "~arch bridge", "~river", "~punt", "~boat"],
    coordinates: { lat: 51.750867, lng: -1.245643 },
    radiusMeters: 60,
    spokenText: `This is Magdalen Bridge, carrying the High Street over the River Cherwell just beside the college. The stone bridge you see dates from the late eighteenth century. Beside it you can hire a punt from the boathouse, and on the first of May it's where the crowds gather at dawn to hear the choir sing from the Great Tower.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/magdalen-bridge.mp3"),
  },
  {
    id: "magdalen-plane",
    name: "The Magdalen Plane",
    category: "tree",
    aliases: ["magdalen plane", "plane tree", "london plane", "sycamore", "~tree", "~woody plant", "~plant", "~trunk", "~branch", "~deciduous"],
    coordinates: { lat: 51.752741, lng: -1.246661 },
    radiusMeters: 30,
    spokenText: `This magnificent tree is the Magdalen Plane, a London plane planted in 1801, so it is more than two hundred years old. London planes are a hybrid, and they're famous for the flaking bark that helps them shed city pollution, which is why they line so many old streets. This one is one of the finest trees in the college.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/magdalen-plane.mp3"),
  },
  {
    id: "magdalen-mulberry",
    name: "The Magdalen Mulberry",
    category: "tree",
    aliases: ["mulberry", "black mulberry", "magdalen mulberry", "~tree", "~fruit tree", "~woody plant", "~plant", "~trunk"],
    coordinates: { lat: 51.7531, lng: -1.2463 },
    radiusMeters: 60,
    spokenText: `Somewhere in the Deer Park is a black mulberry, Morus nigra, which was blown over some time ago but still bears plenty of fruit. Nobody knows quite how old it is, but a drawing from 1783 shows a mulberry at Magdalen, and it may well be the same tree. You can only see it from the path, because visitors can't enter the Deer Park itself.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/magdalen-mulberry.mp3"),
  },
  {
    id: "addisons-walk-trees",
    name: "The trees along Addison's Walk",
    category: "tree",
    aliases: ["~tree", "~trees", "~woodland", "~forest", "~leaf", "~foliage", "~tree lined path", "~avenue", "~woody plant", "~oak", "~willow", "~ash"],
    coordinates: { lat: 51.7531, lng: -1.2436 },
    radiusMeters: 200,
    spokenText: `The trees lining Addison's Walk are a big part of its charm. The National Gardens Scheme describes the grounds as having numerous trees that are a hundred and fifty to two hundred years old, planted densely round the edge of the meadow, and the path itself has been developed as a tree-lined circuit since the late eighteenth century.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/addisons-walk-trees.mp3"),
    treeFallback: true,
  },
  {
    id: "bat-willows",
    name: "The bat willows",
    category: "tree",
    aliases: ["willow", "bat willow", "cricket bat willow", "~tree", "~willow", "~woody plant", "~riverbank"],
    coordinates: { lat: 51.753916, lng: -1.239456 },
    radiusMeters: 90,
    spokenText: `Bat Willow Meadow is named for its willows — the kind whose wood is used to make cricket bats. The old trees were cut down in 2018 because they were so old and had honey fungus, and they've been replanted. Some of the wood from the old trees was put to use making cricket bats, as the meadow's name promised.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/bat-willows.mp3"),
  },
  {
    id: "grove-trees",
    name: "The Grove's great trees",
    category: "tree",
    aliases: ["elm", "oak", "~tree", "~woodland", "~park", "~pasture", "~woody plant"],
    coordinates: { lat: 51.7535, lng: -1.2465 },
    radiusMeters: 120,
    spokenText: `The Grove, the deer park, once had avenues of great trees. A huge oak blew down in 1789, and a famous hybrid elm here, photographed around 1900, was reportedly over forty metres tall — among the biggest trees in Britain — until it was blown down in 1911. Dutch elm disease then swept through in the 1970s and took most of the rest, which is why the park looks so different today.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/grove-trees.mp3"),
  },
  {
    id: "fritillaries",
    name: "The snake's head fritillaries",
    category: "garden",
    aliases: ["fritillary", "snake's head fritillary", "snakes head fritillary", "fritillaria meleagris", "~flower", "~wildflower", "~meadow", "~plant"],
    coordinates: { lat: 51.753144, lng: -1.243753 },
    radiusMeters: 90,
    spokenText: `In spring, the Water Meadow fills with snake's head fritillaries, purple-and-white chequered flowers that look like little bells. They've been recorded here since around 1785, and this is one of the few places in Britain where they grow wild. Please stay on the path and never pick them.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/fritillaries.mp3"),
  },
  {
    id: "addisons-walk",
    name: "Addison's Walk",
    category: "feature",
    aliases: ["addison's walk", "addisons walk", "water walks", "water walk", "~path", "~walkway", "~footpath", "~trail", "~river"],
    coordinates: { lat: 51.753105, lng: -1.243554 },
    radiusMeters: 250,
    spokenText: `Addison's Walk is a loop of about one point two kilometres around a small island in the River Cherwell. It was once simply called the Water Walk; the path may date to the fifteen hundreds, but it took the name of Joseph Addison, a fellow of the college, who loved walking here and wrote about landscape gardening in The Spectator. It became a circuit in the nineteenth century.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/addisons-walk.mp3"),
  },
  {
    id: "water-meadow",
    name: "The Water Meadow",
    category: "garden",
    aliases: ["water meadow", "magdalen meadow", "the meadow", "~meadow", "~grassland", "~field", "~pasture", "~floodplain"],
    coordinates: { lat: 51.753144, lng: -1.243753 },
    radiusMeters: 120,
    spokenText: `This is the Water Meadow, a flood meadow enclosed by Addison's Walk and the River Cherwell. In wet winters it floods, and in spring it's famous for its fritillaries. It has been grazed by deer in the past, and the landscape designer Humphry Repton once proposed flooding it more deliberately, though the college turned that idea down in 1801.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/water-meadow.mp3"),
  },
  {
    id: "deer-park",
    name: "The Deer Park (the Grove)",
    category: "feature",
    aliases: ["deer park", "the grove", "deer", "fallow deer", "~deer", "~park", "~pasture", "~grassland", "~animal"],
    coordinates: { lat: 51.7535, lng: -1.2465 },
    radiusMeters: 120,
    spokenText: `Beyond the fence is the Grove, Magdalen's deer park. Magdalen has the most extensive private grounds of any Oxford college, and a herd of fallow deer has lived here since at least the early eighteenth century — around sixty animals today. Visitors can't walk into the park, but you can watch the deer from the path.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/deer-park.mp3"),
  },
  {
    id: "bat-willow-meadow",
    name: "Bat Willow Meadow",
    category: "garden",
    aliases: ["bat willow meadow", "~meadow", "~grassland", "~field", "~river"],
    coordinates: { lat: 51.753916, lng: -1.239456 },
    radiusMeters: 110,
    spokenText: `This is Bat Willow Meadow, on the far side of the river. It holds a modern sculpture, Y, and beyond it lies the Fellows' Garden, which is private. From the walk you get a lovely view across the water towards it.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/bat-willow-meadow.mp3"),
  },
  {
    id: "y-sculpture",
    name: "Y, the sculpture by Mark Wallinger",
    category: "feature",
    aliases: ["y sculpture", "mark wallinger", "wallinger", "~sculpture", "~steel", "~metal", "~art", "~tree"],
    coordinates: { lat: 51.753537, lng: -1.239439 },
    radiusMeters: 80,
    spokenText: `This branching metal sculpture is called Y, by the artist Mark Wallinger. It's about ten metres high, shaped like a tree, and it was commissioned in 2008 to celebrate the college's five hundred and fiftieth anniversary.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/y-sculpture.mp3"),
  },
  {
    id: "river-cherwell",
    name: "The River Cherwell",
    category: "feature",
    aliases: ["river cherwell", "cherwell", "~river", "~water", "~stream", "~punt", "~bank"],
    coordinates: { lat: 51.752586, lng: -1.242507 },
    radiusMeters: 150,
    spokenText: `The River Cherwell wraps around the college's grounds, splitting into channels that make an island of the Addison's Walk loop. It's why the Water Meadow floods in wet winters, and why the whole walk feels so peaceful and green, right in the middle of the city.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/river-cherwell.mp3"),
  },
  {
    id: "fellows-garden",
    name: "The Fellows' Garden",
    category: "garden",
    aliases: ["fellows' garden", "fellows garden", "~garden", "~lawn", "~hedge"],
    coordinates: { lat: 51.755067, lng: -1.238221 },
    radiusMeters: 90,
    spokenText: `The Fellows' Garden lies north of Bat Willow Meadow, along the bank of the Cherwell. It's private, kept for the college's fellows, so we can only imagine it from here.`,
    audioSource: require("../../../assets/audio/oxford-magdalen/landmarks/fellows-garden.mp3"),
    notOpenToVisitors: true,
  },
];
