/**
 * What a guide says in their own recording of a stop, when it isn't the
 * stop's standard script — keyed like the cues: "<waypoint id>@<guide id>".
 * The subtitles for that recording show these lines (in English: the
 * translated subtitles follow the standard script), and
 * scripts/build-narration-cues.ts times them against the recording.
 * Re-run that script after changing a line here.
 */
export const GUIDE_SCRIPTS: Record<string, string> = {
  "new-college-lane-bridge-of-sighs@ollie": `Welcome to New College Lane, one of Oxford's most enchanting passageways. You're standing beneath the Bridge of Sighs, an iconic Venetian-style bridge completed in 1914. This beautiful structure connects the two sides of Hertford College and was inspired by the famous bridge in Venice. The bridge has become one of Oxford's most photographed landmarks, and legend has it that students who kiss on the bridge are destined to fall in love. The narrow lane itself is lined with historic buildings dating back centuries, and the atmospheric stonework creates a sense of stepping back in time. Notice the intricate architectural details above. The bridge's ornate design reflects Oxford's commitment to beauty alongside scholarship. This location has featured in numerous films and television adaptations of Harry Potter, capturing the Gothic charm that defines the wizarding world. The combination of medieval architecture and romantic atmosphere makes this lane a must-see for any visitor to Oxford.`,

  "bodleian-old-schools-quad@ollie": `You've arrived at the heart of Oxford's intellectual heritage, the Bodleian Library's Old Schools Quadrangle. This magnificent courtyard, built in the early 17th century, represents the pinnacle of Renaissance architecture. The quad is surrounded by iconic buildings, each with its own historical significance. Below us lies the Divinity School, Oxford's oldest teaching room, completed in 1480. The intricate fan-vaulted ceiling is a masterpiece of late Gothic architecture. Look up and you'll see the ornate stonework that has inspired scholars for over five centuries. This room has hosted some of history's most important academic debates and has been featured extensively in the Harry Potter films. The surrounding buildings housed the original university offices and teaching spaces. Walking through this quad, you're literally walking through the corridors where some of the world's greatest minds studied and taught. The atmosphere here is thick with history. Every stone tells a story of centuries.`,

  "christ-church-tom-tower@ollie": `Welcome to Christ Church, one of Oxford's most prestigious colleges, and a location deeply connected to the Harry Potter saga. The imposing Tom Tower, designed by Sir Christopher Wren, dominates the skyline and is one of Oxford's most recognisable landmarks. The tower stands 137 feet tall and is crowned with an octagonal cupola. Every evening at 9:05pm, the Great Bell, known as Great Tom, rings 101 times, a tradition that has continued for over 300 years. The number 101 represents the original number of scholars in the college. Christ Church's cloisters and staircases served as the inspiration for Hogwarts School of Witchcraft and Wizardry. The dining hall here was used as the model for the Great Hall in the films. The college's stunning Gothic Revival architecture perfectly captures the magical atmosphere of Hogwarts. The cathedral, located within the college grounds, dates back to the 12th century. Walking through these spaces, you can almost imagine yourself as a student at Hogwarts.`,

  "turf-tavern@ollie": `You've discovered one of Oxford's best-kept secrets, the Turf Tavern, nestled in a hidden alley between Holywell and Bath Place. This historic pub dates back to 1612 and has barely changed since. The low ceilings, tiny rooms and cosy atmosphere create an authentic 17th-century experience. The Turf is famous for being one of the smallest and most atmospheric pubs in Oxford, with genuine history woven into every beam and stone. The beer garden offers a peaceful retreat, with views of surrounding historic buildings. Many notable figures have enjoyed a drink here, and the pub remains largely unchanged from its original form. The walls display memorabilia and photographs, capturing centuries of Oxford life. This tavern represents the authentic Oxford experience. A place where students, scholars and visitors have gathered for over 400 years to relax, discuss ideas and enjoy the camaraderie of this ancient university town.`,
};
