/**
 * Spanish subtitles for the English narration, one line per English sentence
 * (see narration/sentences.ts), keyed by waypoint id.
 */
export const es: Record<string, string[]> = {
  // --- Magdalen College (oxford-magdalen) ---
  "lodge-and-welcome": [
    "Bienvenido al colegio Magdalen.",
    "Se escribe M-A-G-D-A-L-E-N y se pronuncia «Módlin»: una de esas rarezas de Oxford que nunca adivinarías por la ortografía.",
    "El colegio lo fundó en 1458 William Waynflete, obispo de Winchester y lord canciller de Inglaterra, en el solar de un hospital medieval, el Hospital de San Juan Bautista, disuelto el año anterior.",
    "Entre sus antiguos alumnos están Oscar Wilde, que estudió aquí en la década de 1870, y C. S. Lewis, profesor del colegio durante veintinueve años, de 1925 a 1954.",
    "El poeta Seamus Heaney, premio Nobel, también fue miembro del colegio.",
    "Unas normas antes de entrar.",
    "Necesitarás una entrada de visitante del colegio, que puedes comprar el mismo día o por internet.",
    "Por favor, no te salgas de los caminos ni pises el césped, no subas por ninguna escalera ni entres donde ponga «privado», y deja el dron en casa: solo se admiten perros guía.",
    "Cuando cruces la portería, entra en el primer patio, St John's Quad.",
  ],
  "st-johns-quad": [
    "Estás en St John's Quad, un primer patio de forma irregular que debe su nombre al Hospital de San Juan Bautista, que ocupaba este terreno antes que el colegio.",
    "Mira a tu alrededor y verás el antiguo Grammar Hall, que recuerda la escuela que Waynflete fundó junto a su colegio: Magdalen College School, que abrió en 1480.",
    "Y hay algo bastante insólito: un púlpito de piedra construido para usarse al aire libre.",
    "Por tradición, se predica un sermón desde él al aire libre en torno a la fiesta de San Juan Bautista, en junio, una costumbre que evoca el hospital que hubo aquí.",
    "La torre del Fundador, justo aquí, es el paso hacia el claustro, pero antes, el corazón del colegio.",
    "Gírate hacia la capilla.",
  ],
  chapel: [
    "Esta es la capilla del colegio, construida entre 1474 y 1480, y desde entonces ha sido el centro de la vida de Magdalen.",
    "Su coro es famoso en todo el mundo y canta un oficio a las seis casi todas las tardes durante el curso, y todo el mundo es bienvenido, incluso fuera del horario de visitas.",
    "La capilla puede cerrar por oficios o ensayos, así que si la puerta está cerrada, esta parada funciona igual de bien desde la entrada.",
    "Si puedes entrar, busca tres cosas.",
    "Detrás del altar hay un gran retablo de piedra, diseñado por Lewis Cottingham en la década de 1830, con tres pisos de trece hornacinas llenas de figuras talladas por Thomas Earp en 1864 y 1865.",
    "Sobre tu cabeza hay un techo que parece una bóveda de piedra, pero en realidad es de yeso, obra de James Wyatt en 1790.",
    "Y busca la vidriera de Francis Eginton, de 1792, que muestra el Juicio Final en tonos grises.",
    "Por favor, guarda silencio y respeto, porque es un lugar de culto.",
    "Cuando estés listo, sal a Chaplain's Quad, el patio del Capellán.",
  ],
  "chaplains-quad-and-tower": [
    "Estás en Chaplain's Quad, un patio más o menos triangular que corre junto a la capilla y el comedor hasta la Gran Torre.",
    "Esa forma triangular quedó así una vez terminada la torre.",
    "La Gran Torre es el monumento más famoso del colegio.",
    "Mide ciento cuarenta y cuatro pies de altura, unos cuarenta y cuatro metros.",
    "Su construcción empezó en 1492, cuando el doctor Richard Mayew colocó la primera piedra el 9 de agosto, y se terminó en 1509 bajo el maestro de obras William Raynold.",
    "Dentro cuelgan diez campanas; la más pesada se fundió en 1623.",
    "Cada 1 de mayo, a las seis de la mañana, el coro canta desde lo más alto. Volveremos a eso al final del recorrido.",
    "A tu lado está el comedor, el Hall, y el Old Kitchen Bar, en lo que fueron las cocinas del hospital.",
    "Normalmente ambos están abiertos a los visitantes, aunque el comedor puede cerrar a la hora de comer.",
    "A continuación, vuelve por la torre del Fundador hasta el claustro.",
  ],
  cloister: [
    "Al cruzar la torre del Fundador, con sus tallas, sus pináculos y su bóveda ricamente labrada, sales al claustro, al que a veces llaman el Gran Patio.",
    "Lo construyó entre 1474 y 1480 el maestro cantero William Orchard, y es la imagen clásica del Oxford medieval: una galería cubierta de piedra alrededor de un cuadrado de césped.",
    "Ahora mira hacia arriba.",
    "Unas pequeñas figuras talladas se asoman por la piedra, y son de 1508.",
    "Las llaman los jeroglíficos, y cada una representa una virtud o un vicio.",
    "Hay un león para el valor, un pelícano para el cariño, una mantícora para el orgullo, una pareja de boxeadores para la discordia y una lamia para la lujuria.",
    "A ver cuántas encuentras.",
    "Un dato curioso: todo el lado norte se derribó en 1822, alegando que estaba en mal estado, y se reconstruyó poco después.",
    "Sal por el lado norte del claustro y busca un árbol muy grande.",
  ],
  "magdalen-plane": [
    "Aquí está el primero de los famosos árboles del colegio: el plátano de Magdalen.",
    "Es un plátano de sombra, plantado en 1801, así que tiene más de doscientos años.",
    "Estos plátanos son un híbrido, conocidos por su corteza que se desprende en placas y les ayuda a librarse de la contaminación de la ciudad; por eso bordean tantas calles antiguas.",
    "Este es uno de los mejores árboles del colegio, y se alza detrás de los edificios principales.",
    "Sigue adelante y llegarás a una larga fachada clásica: el New Building, el Edificio Nuevo.",
  ],
  "new-building": [
    "Este largo edificio clásico se llama el Edificio Nuevo, aunque tiene casi trescientos años.",
    "Se empezó a construir en 1733, según los planos que Edward Holdsworth trazó en 1731, en el majestuoso estilo palladiano, con una columnata a lo largo de la fachada.",
    "Iba a ser uno de los lados de un enorme patio nuevo, pero el resto nunca se construyó, y Thomas Harrison remató los extremos en 1824.",
    "Hoy alberga a estudiantes y profesores, y también la bodega del colegio.",
    "Desde aquí dejamos atrás los edificios y tomamos el camino hacia el agua.",
    "Sigue las indicaciones hacia Addison's Walk, el paseo de Addison.",
  ],
  "addisons-walk": [
    "Has llegado al paseo de Addison, un circuito de aproximadamente 1,2 kilómetros alrededor de una pequeña isla en el río Cherwell.",
    "Antes se llamaba simplemente el Paseo del Agua.",
    "El camino puede remontarse al siglo XVI, pero tomó su nombre en el siglo XIX de Joseph Addison, miembro del colegio al que le encantaba pasear por aquí y que escribió sobre jardinería paisajista en The Spectator.",
    "Se convirtió en un circuito en el siglo XIX.",
    "Fíjate en los árboles que lo bordean.",
    "En los terrenos hay numerosos árboles de entre ciento cincuenta y doscientos años, plantados densamente alrededor del borde del prado.",
    "Tómate tu tiempo, no te salgas del camino y síguelo en el sentido de las agujas del reloj, con el parque de los ciervos a tu izquierda.",
  ],
  "deer-park-and-mulberry": [
    "A tu izquierda está el Grove, el parque de ciervos de Magdalen.",
    "Magdalen tiene los terrenos privados más extensos de todos los colegios de Oxford, y una manada de gamos vive aquí al menos desde principios del siglo XVIII: hoy son unos sesenta animales.",
    "Los visitantes no pueden entrar en el parque, pero puedes ver los ciervos desde el camino.",
    "El Grove estuvo lleno de grandes árboles.",
    "Un enorme roble cayó por el viento en 1789.",
    "Un famoso olmo híbrido, fotografiado hacia 1900, al parecer medía más de cuarenta metros, uno de los árboles más grandes de Gran Bretaña, hasta que el viento lo derribó en 1911.",
    "Después, la grafiosis del olmo arrasó en los años setenta y se llevó casi todos los demás.",
    "En algún lugar del parque hay una morera negra que el viento tumbó hace mucho, pero que todavía da fruto.",
    "Nadie sabe exactamente cuántos años tiene, pero un dibujo de 1783 muestra una morera en Magdalen, y podría ser el mismo árbol.",
    "Sigue caminando hasta la esquina del circuito.",
  ],
  "holywell-ford-and-lewis": [
    "Esta esquina del circuito, cerca de la puerta de Holywell Ford, pertenece a C. S. Lewis.",
    "Fue miembro de Magdalen y profesor de Literatura Inglesa aquí de 1925 a 1954, y paseaba a menudo por este camino con amigos, entre ellos J. R. R. Tolkien y Hugo Dyson, como parte del grupo de escritores conocido como los Inklings.",
    "Escribió un poema sobre este mismo paseo, y una placa a lo largo del camino lo recuerda.",
    "La noche del 19 de septiembre de 1931, una larga conversación con Tolkien y Dyson, en parte en este paseo, ayudó a Lewis a pasar de creer en Dios al cristianismo: un punto de inflexión en la vida del autor de Las Crónicas de Narnia.",
    "Busca la placa por el camino.",
    "Después, sigue el sendero hacia el este, junto al río.",
  ],
  "bat-willow-meadow": [
    "Al otro lado del agua está Bat Willow Meadow, el prado de los sauces de bate.",
    "Su nombre viene de sus sauces, los de la madera con la que se fabrican los bates de críquet.",
    "Los árboles viejos se talaron en 2018 porque eran muy viejos y tenían armilaria, y se han vuelto a plantar.",
    "Parte de la madera se usó para hacer bates de críquet, tal como prometía el nombre.",
    "La alta escultura ramificada se llama Y, del artista Mark Wallinger.",
    "Mide unos diez metros, tiene forma de árbol y se encargó en 2008 para el 550 aniversario del colegio.",
    "Más allá del prado, a la orilla del río, está el jardín de los profesores, que es privado, así que solo podemos imaginarlo.",
    "Ahora vuelve por el otro lado del circuito.",
  ],
  "water-meadow": [
    "El campo abierto junto al que caminas es el Water Meadow, un prado inundable rodeado por el circuito y por el río Cherwell.",
    "En los inviernos lluviosos se inunda, y en primavera se convierte en una de las estampas más famosas de Oxford.",
    "Es por las fritilarias o flores de tablero de damas: flores moradas y blancas con dibujo a cuadros y forma de campanita.",
    "Están documentadas aquí desde aproximadamente 1785, y este es uno de los pocos lugares de Gran Bretaña donde crecen en estado silvestre.",
    "Si vienes en primavera, por favor, no te salgas del camino y nunca las arranques.",
    "El paisajista Humphry Repton propuso una vez inundar el prado de forma más deliberada, pero el colegio rechazó la idea en 1801.",
    "Puede que veas la Gran Torre asomar por encima de los árboles, delante de ti.",
    "Sigue el camino de vuelta al colegio.",
  ],
  "magdalen-bridge": [
    "Has salido del colegio y estás en el puente de Magdalen, en la High Street, que es vía pública: mira atrás y verás la Gran Torre de la que hemos estado hablando.",
    "Cada 1 de mayo, a las seis de la mañana, el coro del colegio, con sus niños cantores, sube a lo alto de esa torre y canta desde allí un himno en latín, el Hymnus Eucharisticus.",
    "Se dice que la tradición se remonta a la época de Enrique VII.",
    "Una gran multitud se reúne en la High Street y en este puente para escucharlo, y cuando termina el canto, repican las campanas.",
    "El pintor William Holman Hunt retrató la ceremonia en un famoso cuadro en 1890.",
    "El puente de piedra es de finales del siglo XVIII.",
    "En los últimos años se ha cerrado esa mañana para desalentar el tradicional salto al río, que ha mandado a gente al hospital; así que, si estás aquí el 1 de mayo, escucha, pero no saltes.",
    "Aquí termina el recorrido.",
    "Gracias por recorrer Magdalen conmigo.",
    "Si te apetece ver el colegio desde el agua, puedes alquilar una batea en el embarcadero que hay justo al lado del puente.",
  ],
};
