/**
 * French subtitles for the English narration, one line per English sentence
 * (see narration/sentences.ts), keyed by waypoint id.
 */
export const fr: Record<string, string[]> = {
  // --- Magdalen College (oxford-magdalen) ---
  "lodge-and-welcome": [
    "Bienvenue à Magdalen College.",
    "Ça s'écrit M-A-G-D-A-L-E-N et ça se prononce « Maudlin » : une de ces bizarreries d'Oxford qu'on ne devinerait jamais à l'orthographe.",
    "Le collège a été fondé en 1458 par William Waynflete, évêque de Winchester et lord chancelier d'Angleterre, sur le site d'un hôpital médiéval, l'hôpital Saint-Jean-Baptiste, dissous l'année précédente.",
    "Parmi ses anciens figurent Oscar Wilde, qui y a étudié dans les années 1870, et C. S. Lewis, enseignant au collège pendant vingt-neuf ans, de 1925 à 1954.",
    "Le poète Seamus Heaney, prix Nobel, en a aussi été membre.",
    "Quelques règles avant d'entrer.",
    "Il te faut un billet de visiteur du collège, à acheter sur place ou en ligne.",
    "Merci de rester sur les allées et de ne pas marcher sur la pelouse, de ne monter aucun escalier ni entrer là où c'est marqué privé, et de laisser ton drone à la maison : seuls les chiens guides sont admis.",
    "Une fois passé la loge, entre dans la première cour, St John's Quad.",
  ],
  "st-johns-quad": [
    "Tu es dans St John's Quad, une première cour de forme irrégulière, nommée d'après l'hôpital Saint-Jean-Baptiste qui occupait ce terrain avant le collège.",
    "Regarde autour de toi et tu verras l'ancien Grammar Hall, souvenir de l'école que Waynflete fonda à côté de son collège : Magdalen College School, ouverte en 1480.",
    "Et il y a quelque chose d'assez inhabituel : une chaire en pierre construite pour être utilisée en plein air.",
    "Par tradition, un sermon y est prêché en plein air autour de la fête de la Saint-Jean-Baptiste, en juin, une coutume qui rappelle l'hôpital d'autrefois.",
    "La tour du Fondateur, juste ici, mène au cloître, mais d'abord, le cœur du collège.",
    "Tourne-toi vers la chapelle.",
  ],
  chapel: [
    "Voici la chapelle du collège, construite entre 1474 et 1480, et depuis le centre de la vie de Magdalen.",
    "Son chœur est mondialement célèbre et chante un office à six heures la plupart des soirs pendant l'année universitaire, et tout le monde est bienvenu, même en dehors des heures de visite.",
    "La chapelle peut fermer pour des offices ou des répétitions ; si la porte est close, cet arrêt fonctionne tout aussi bien depuis le seuil.",
    "Si tu peux entrer, cherche trois choses.",
    "Derrière l'autel se trouve un grand retable de pierre, conçu par Lewis Cottingham dans les années 1830, avec trois rangées de treize niches garnies de figures sculptées par Thomas Earp en 1864 et 1865.",
    "Au-dessus de toi, un plafond qui ressemble à une voûte de pierre mais qui est en réalité en plâtre, posé par James Wyatt en 1790.",
    "Et cherche le vitrail de Francis Eginton, de 1792, qui montre le Jugement dernier en nuances de gris.",
    "Merci de rester calme et respectueux : c'est un lieu de culte.",
    "Quand tu es prêt, sors dans Chaplain's Quad, la cour du Chapelain.",
  ],
  "chaplains-quad-and-tower": [
    "Tu es dans Chaplain's Quad, une cour à peu près triangulaire qui longe la chapelle et le réfectoire jusqu'à la Grande Tour.",
    "Cette forme triangulaire est apparue une fois la tour achevée.",
    "La Grande Tour est le monument le plus célèbre du collège.",
    "Elle mesure cent quarante-quatre pieds, soit environ quarante-quatre mètres.",
    "La construction a commencé en 1492, quand le Dr Richard Mayew posa la première pierre le 9 août, et s'est achevée en 1509 sous le maître maçon William Raynold.",
    "Dix cloches y sont suspendues, la plus lourde fondue en 1623.",
    "Chaque 1er mai, à six heures du matin, le chœur chante tout en haut ; nous y reviendrons à la fin de la visite.",
    "À côté se trouvent le réfectoire, le Hall, et l'Old Kitchen Bar, dans les anciennes cuisines de l'hôpital.",
    "Les deux sont normalement ouverts aux visiteurs, mais le réfectoire peut fermer vers l'heure du déjeuner.",
    "Ensuite, repasse par la tour du Fondateur jusqu'au cloître.",
  ],
  cloister: [
    "En passant la tour du Fondateur, avec ses sculptures, ses pinacles et sa voûte richement ouvragée, tu débouches dans le cloître, parfois appelé la Grande Cour.",
    "Il a été construit entre 1474 et 1480 par le maçon William Orchard, et c'est l'image classique d'Oxford au Moyen Âge : une galerie de pierre couverte autour d'un carré de pelouse.",
    "Maintenant, lève les yeux.",
    "De petites figures sculptées se perchent le long de la pierre ; elles datent de 1508.",
    "On les surnomme les hiéroglyphes, et chacune représente une vertu ou un vice.",
    "Il y a un lion pour le courage, un pélican pour l'affection, une manticore pour l'orgueil, deux boxeurs pour la querelle et une lamie pour la luxure.",
    "Vois combien tu peux en repérer.",
    "Détail curieux : tout le côté nord a été démoli en 1822, sous prétexte qu'il était délabré, puis reconstruit peu après.",
    "Sors par le côté nord du cloître et cherche un très grand arbre.",
  ],
  "magdalen-plane": [
    "Voici le premier des arbres célèbres du collège : le platane de Magdalen.",
    "C'est un platane commun, planté en 1801 : il a donc plus de deux cents ans.",
    "Ces platanes sont des hybrides, connus pour leur écorce qui s'écaille et les aide à se débarrasser de la pollution urbaine ; c'est pourquoi ils bordent tant de vieilles rues.",
    "Celui-ci compte parmi les plus beaux arbres du collège, et il se dresse derrière les bâtiments principaux.",
    "Continue, et tu arriveras à une longue façade classique : le New Building, le Nouveau Bâtiment.",
  ],
  "new-building": [
    "Ce long bâtiment classique s'appelle le Nouveau Bâtiment, bien qu'il ait presque trois cents ans.",
    "Sa construction a commencé en 1733, d'après des plans d'Edward Holdsworth datant de 1731, dans le grand style palladien, avec une colonnade sur toute la façade.",
    "Il devait former un côté d'une immense nouvelle cour, mais le reste n'a jamais été construit, et Thomas Harrison en a achevé les extrémités en 1824.",
    "Aujourd'hui, il loge des étudiants et des enseignants, ainsi que la cave à vin du collège.",
    "D'ici, nous laissons les bâtiments derrière nous et prenons le chemin vers l'eau.",
    "Suis les panneaux vers Addison's Walk, la promenade d'Addison.",
  ],
  "addisons-walk": [
    "Te voici sur la promenade d'Addison, une boucle d'environ 1,2 kilomètre autour d'une petite île de la rivière Cherwell.",
    "On l'appelait autrefois simplement la Promenade de l'Eau.",
    "Le chemin remonte peut-être au XVIe siècle, mais il a pris son nom au XIXe siècle de Joseph Addison, membre du collège qui adorait s'y promener et qui écrivit sur l'art des jardins dans The Spectator.",
    "Il est devenu une boucle au XIXe siècle.",
    "Regarde les arbres qui la bordent.",
    "Le domaine compte de nombreux arbres de cent cinquante à deux cents ans, plantés serrés autour du pré.",
    "Prends ton temps, reste sur le chemin et suis-le dans le sens des aiguilles d'une montre, avec le parc aux daims sur ta gauche.",
  ],
  "deer-park-and-mulberry": [
    "Sur ta gauche se trouve le Grove, le parc aux daims de Magdalen.",
    "Magdalen possède le plus vaste domaine privé de tous les collèges d'Oxford, et un troupeau de daims y vit au moins depuis le début du XVIIIe siècle : une soixantaine de bêtes aujourd'hui.",
    "Les visiteurs ne peuvent pas entrer dans le parc, mais tu peux observer les daims depuis le chemin.",
    "Le Grove était autrefois rempli de grands arbres.",
    "Un énorme chêne a été abattu par le vent en 1789.",
    "Un célèbre orme hybride, photographié vers 1900, aurait dépassé quarante mètres, parmi les plus grands arbres de Grande-Bretagne, jusqu'à sa chute en 1911.",
    "Puis la graphiose de l'orme a frappé dans les années 1970 et emporté presque tous les autres.",
    "Quelque part dans le parc, un mûrier noir renversé il y a longtemps donne encore des fruits.",
    "Personne ne sait vraiment quel âge il a, mais un dessin de 1783 montre un mûrier à Magdalen, et ce pourrait être le même arbre.",
    "Continue jusqu'au coin de la boucle.",
  ],
  "holywell-ford-and-lewis": [
    "Ce coin de la boucle, près de la porte de Holywell Ford, appartient à C. S. Lewis.",
    "Il fut membre de Magdalen et professeur d'anglais ici de 1925 à 1954, et il parcourait souvent ce chemin avec des amis, dont J. R. R. Tolkien et Hugo Dyson, au sein du groupe d'écrivains appelé les Inklings.",
    "Il a écrit un poème sur cette promenade même, et une plaque le long du parcours le commémore.",
    "Et dans la nuit du 19 septembre 1931, une longue conversation avec Tolkien et Dyson, en partie sur ce chemin, aida Lewis à passer de la croyance en Dieu au christianisme : un tournant dans la vie de l'auteur du Monde de Narnia.",
    "Cherche la plaque en marchant.",
    "Puis suis le chemin vers l'est, le long de la rivière.",
  ],
  "bat-willow-meadow": [
    "De l'autre côté de l'eau se trouve Bat Willow Meadow, le pré des saules à battes.",
    "Son nom vient de ses saules, ceux dont le bois sert à fabriquer les battes de cricket.",
    "Les vieux arbres ont été abattus en 2018 car ils étaient très âgés et atteints de pourridié, et on en a replanté.",
    "Une partie du bois a servi à fabriquer des battes de cricket, comme le promettait le nom.",
    "La haute sculpture ramifiée s'appelle Y, de l'artiste Mark Wallinger.",
    "Elle mesure environ dix mètres, a la forme d'un arbre, et a été commandée en 2008 pour le 550e anniversaire du collège.",
    "Au-delà du pré, au bord de la rivière, se trouve le jardin des Fellows ; il est privé, on ne peut que l'imaginer.",
    "Maintenant, reviens par l'autre côté de la boucle.",
  ],
  "water-meadow": [
    "Le champ ouvert que tu longes est le Water Meadow, un pré inondable entouré par la boucle et la rivière Cherwell.",
    "Les hivers pluvieux, il est inondé, et au printemps il devient l'un des spectacles les plus célèbres d'Oxford.",
    "C'est grâce aux fritillaires pintades : des fleurs violettes et blanches en damier, en forme de petites clochettes.",
    "Elles sont signalées ici depuis 1785 environ, et c'est l'un des rares endroits de Grande-Bretagne où elles poussent à l'état sauvage.",
    "Si tu viens au printemps, reste sur le chemin et ne les cueille jamais.",
    "Le paysagiste Humphry Repton proposa un jour d'inonder le pré de façon plus délibérée, mais le collège refusa en 1801.",
    "Tu apercevras peut-être la Grande Tour au-dessus des arbres, devant toi.",
    "Suis le chemin pour revenir dans le collège.",
  ],
  "magdalen-bridge": [
    "Tu as quitté le collège et tu te trouves sur le pont de Magdalen, sur la High Street, voie publique : retourne-toi et tu verras la Grande Tour dont nous avons parlé.",
    "Chaque 1er mai, à six heures du matin, le chœur du collège, avec ses jeunes choristes, monte au sommet de cette tour et y chante un hymne latin, l'Hymnus Eucharisticus.",
    "La tradition remonterait à l'époque d'Henri VII.",
    "Une foule nombreuse se rassemble sur la High Street et sur ce pont pour écouter, et quand le chant se termine, les cloches sonnent.",
    "Le peintre William Holman Hunt a représenté la cérémonie dans un célèbre tableau en 1890.",
    "Le pont de pierre date de la fin du XVIIIe siècle.",
    "Ces dernières années, il a été fermé ce matin-là pour décourager le saut traditionnel dans la rivière, qui a envoyé des gens à l'hôpital ; alors si tu es là le 1er mai, écoute, mais ne saute pas.",
    "C'est la fin de la visite.",
    "Merci d'avoir parcouru Magdalen avec moi.",
    "Tu peux louer une barque à perche au hangar à bateaux juste à côté du pont, si tu as envie de voir le collège depuis l'eau.",
  ],
};
