/** Restaurants on FoodStep's maps, per city and cuisine. Only Manchester's
 * Mexican so far, as the pattern to copy for the rest.
 *
 * Mexican: checked in October 2026 against TripAdvisor's Mexican list, Manchester's
 * Finest (March 2026), The Manc (June 2026) and That's Up (March 2026), and
 * kept to places with 2026 evidence that they're open (closed ones like
 * El Taquero and Liquor & Burn left out). City centre only, so they all sit
 * in a zone (foodStepZones.ts); at most 6 per zone. Positions and addresses
 * are from OpenStreetMap where it has the restaurant, otherwise the
 * restaurant's published address; the Arndale and Kampus ones are placed by
 * hand inside their building. Descriptions are our own. No ratings yet:
 * TripAdvisor's and Google's can only be shown through their licensed APIs.
 *
 * Italian: picked the same way in October 2026, mostly from TripAdvisor's
 * Italian list (city-centre ones), plus Manchester's Finest and other 2026
 * guides for Purezza, Ciaooo, Honest Crust, Onda and Sicilian NQ. */

export interface FoodStepRestaurant {
  id: string;
  name: string;
  /** Its neighbourhood: an id from foodStepZones.ts. */
  zone: string;
  /** Shown under the name, e.g. "Mexican" or "Mexican & Japanese". */
  style: string;
  address: string;
  lat: number;
  lng: number;
  description: string;
  /** From a licensed source, with its name for the credit line. */
  rating?: { score: number; outOf: number; source: string };
}

const RESTAURANTS: Record<string, FoodStepRestaurant[]> = {
  "manchester/mexican": [
    // Northern Quarter
    {
      id: "birria-brothers",
      zone: "northern-quarter",
      name: "Birria Brothers",
      style: "Mexican",
      address: "Koffee Pot, 84–86 Oldham Street, M4 1LE",
      lat: 53.48414,
      lng: -2.23325,
      description: "Takes over the Koffee Pot from 4pm every day: fried birria tacos with spiced consommé, plus birria ramen. A pop-up that once drew four-hour queues.",
    },
    {
      id: "boogalu",
      zone: "northern-quarter",
      name: "Boogalú",
      style: "Mexican & Latin",
      address: "12 Tariff Street, M1 2FF",
      lat: 53.48125,
      lng: -2.23211,
      description: "A rum and tequila bar with a taqueria: tacos, nachos and grilled prawns, and a lively bottomless brunch at weekends.",
    },
    {
      id: "el-jefe-birria",
      zone: "northern-quarter",
      name: "El Jefe Birria",
      style: "Mexican",
      address: "MALA, 8 Dale Street, M1 1JA",
      lat: 53.48201,
      lng: -2.23498,
      description: "Messy, many-napkin birria quesadillas stuffed with slow-braised meat, stretchy cheese and properly spicy salsa.",
    },
    // Mackie Mayor & Smithfield
    {
      id: "picos-tacos",
      zone: "mackie-mayor",
      name: "Pico's Tacos",
      style: "Mexican",
      address: "Mackie Mayor, 1 Eagle Street, M4 5BU",
      lat: 53.48549,
      lng: -2.23486,
      description: "A taco counter in the Mackie Mayor food hall, pressing its own corn tortillas, with creative fillings, loaded nachos and margaritas.",
    },
    // City Centre
    {
      id: "panchos-burritos",
      zone: "city-centre",
      name: "Pancho's Burritos",
      style: "Mexican",
      address: "Arndale Food Market, 49 High Street, M4 3AH",
      lat: 53.4834,
      lng: -2.2393,
      description: "A market stall making burritos, tacos and enchiladas from family recipes since 2009. Cheap, quick and much loved.",
    },
    {
      id: "barburrito-arndale",
      zone: "city-centre",
      name: "Barburrito (Arndale)",
      style: "Mexican",
      address: "Manchester Arndale, M4 3AQ",
      lat: 53.4838,
      lng: -2.2414,
      description: "The Manchester-born burrito chain's big Arndale branch: quick, filling burritos and bowls built to order.",
    },
    {
      id: "tortilla-arndale",
      zone: "city-centre",
      name: "Tortilla (Arndale)",
      style: "Mexican",
      address: "Manchester Arndale, M4 3AQ",
      lat: 53.483,
      lng: -2.2407,
      description: "Fast-casual burritos, tacos and nachos you build yourself, handy for a shopping break.",
    },
    {
      id: "taco-bell-market-street",
      zone: "city-centre",
      name: "Taco Bell",
      style: "Tex-Mex",
      address: "32 Market Street, M2 1NP",
      lat: 53.48248,
      lng: -2.24315,
      description: "The American fast-food chain's crunchy tacos, burritos and quesadillas, open late.",
    },
    {
      id: "sandinista",
      zone: "city-centre",
      name: "Sandinista",
      style: "Mexican & Latin",
      address: "2 Old Bank Street, M2 7PF",
      lat: 53.48215,
      lng: -2.24491,
      description: "A late-night dive bar off St Ann's Square serving tacos and Latin street food with tequila cocktails.",
    },
    // Piccadilly
    {
      id: "don-tacos",
      zone: "piccadilly",
      name: "Don Tacos",
      style: "Mexican",
      address: "Unit E3, One Piccadilly Gardens, M1 1RG",
      lat: 53.48018,
      lng: -2.23641,
      description: "Says it brought the birria taco to the UK. Come for slow-cooked birria tacos with consommé for dunking, and cheesy quesadillas.",
    },
    {
      id: "barburrito-piccadilly",
      zone: "piccadilly",
      name: "Barburrito (Piccadilly Gardens)",
      style: "Mexican",
      address: "One Piccadilly Gardens, M1 1RG",
      lat: 53.48055,
      lng: -2.23675,
      description: "Where Barburrito started in 2005: build-your-own burritos, bowls and tacos, fast.",
    },
    {
      id: "zambrero-piccadilly",
      zone: "piccadilly",
      name: "Zambrero (Piccadilly)",
      style: "Mexican",
      address: "7–9 Piccadilly, M1 1LZ",
      lat: 53.48177,
      lng: -2.23781,
      description: "An Australian chain doing casual counter-service burritos, tacos and quesadillas.",
    },
    {
      id: "tortilla-piccadilly",
      zone: "piccadilly",
      name: "Tortilla (Piccadilly Station)",
      style: "Mexican",
      address: "Piccadilly Station Approach, M1 2GH",
      lat: 53.47756,
      lng: -2.23107,
      description: "Burritos and tacos to go, right by the station: good for a bite before a train.",
    },
    // The Village
    {
      id: "madre",
      zone: "the-village",
      name: "Madre",
      style: "Mexican",
      address: "Minshull House, 47 Chorlton Street, M1 3FY",
      lat: 53.47737,
      lng: -2.23542,
      description: "A modern Mexican kitchen and cocktail bar: antojitos, oysters, the grill and creative tacos. Crispy pork belly is a favourite.",
    },
    {
      id: "salon-madre",
      zone: "the-village",
      name: "Salón Madre",
      style: "Mexican",
      address: "49 Chorlton Street, Kampus, M1 3FY",
      lat: 53.47758,
      lng: -2.23515,
      description: "Madre's laid-back sibling: a tequila bar and pool hall with Mexican street food, tucked into Kampus.",
    },
    // Deansgate & St Peter's
    {
      id: "peter-street-kitchen",
      zone: "deansgate-st-peters",
      name: "Peter Street Kitchen",
      style: "Mexican & Japanese",
      address: "Free Trade Hall, Peter Street, M2 5GP",
      lat: 53.4779,
      lng: -2.2473,
      description: "An upmarket restaurant in the historic Free Trade Hall, pairing Mexican and Japanese cooking.",
    },
    {
      id: "las-iguanas",
      zone: "deansgate-st-peters",
      name: "Las Iguanas",
      style: "Latin American",
      address: "84 Deansgate, M3 2ER",
      lat: 53.48247,
      lng: -2.24713,
      description: "A lively Latin American chain with Mexican favourites like sizzling fajitas, and a long cocktail list.",
    },
    {
      id: "zambrero-cross-street",
      zone: "deansgate-st-peters",
      name: "Zambrero (Cross Street)",
      style: "Mexican",
      address: "59 Cross Street, M2 4JW",
      lat: 53.48028,
      lng: -2.24497,
      description: "Zambrero's second city-centre counter: quick burritos, bowls and quesadillas near the Town Hall.",
    },
    {
      id: "revolucion-de-cuba",
      zone: "deansgate-st-peters",
      name: "Revolución de Cuba",
      style: "Cuban & Latin",
      address: "11 Peter Street, M2 5QR",
      lat: 53.47832,
      lng: -2.24895,
      description: "A big, noisy rum bar with live music and Latin plates, including burritos, tacos and loaded nachos.",
    },
    // Spinningfields
    {
      id: "ocasa",
      zone: "spinningfields",
      name: "OCASA",
      style: "Mexican",
      address: "1 The Avenue, Spinningfields, M3 3AP",
      lat: 53.4802,
      lng: -2.2502,
      description: "A Tulum-inspired Mexican restaurant and tequila bar, with modern takes on Mexico City street food.",
    },
    // Oxford Street
    {
      id: "listo-burrito",
      zone: "oxford-street",
      name: "Listo Burrito",
      style: "Mexican",
      address: "91–93 Oxford Street, M1 6ET",
      lat: 53.47534,
      lng: -2.24152,
      description: "Quick, build-your-own burritos and bowls, popular for being filling and good value.",
    },
    {
      id: "tortilla-oxford-street",
      zone: "oxford-street",
      name: "Tortilla (Oxford Street)",
      style: "Mexican",
      address: "50 Oxford Street, M1 5EJ",
      lat: 53.476,
      lng: -2.24215,
      description: "Build-your-own burritos, tacos and nachos on the way between St Peter's Square and the universities.",
    },
    {
      id: "casa-mexica",
      zone: "oxford-street",
      name: "Casa Mexica",
      style: "Tex-Mex",
      address: "Chester Street, M1 5QS",
      lat: 53.47242,
      lng: -2.2402,
      description: "A colourful, casual spot for burritos and Tex-Mex classics, with bright murals on the walls.",
    },
  ],
  "manchester/italian": [
    // Northern Quarter
    {
      id: "purezza",
      zone: "northern-quarter",
      name: "Purezza",
      style: "Vegan Italian",
      address: "75–77 High Street, M4 1FS",
      lat: 53.48445,
      lng: -2.23762,
      description: "The UK's original plant-based pizzeria: sourdough pizzas with vegan cheeses made in-house, in a big Northern Quarter space.",
    },
    {
      id: "sicilian-nq",
      zone: "northern-quarter",
      name: "Sicilian NQ",
      style: "Sicilian",
      address: "14 Turner Street, M4 1DZ",
      lat: 53.48382,
      lng: -2.23773,
      description: "A small, family-style Sicilian bistro known for its arancini, cannoli and tiramisu.",
    },
    // Mackie Mayor & Smithfield
    {
      id: "noi-quattro",
      zone: "mackie-mayor",
      name: "Noi Quattro",
      style: "Pizza",
      address: "120 High Street, M4 1HQ",
      lat: 53.48507,
      lng: -2.23543,
      description: "Naples-style pizza with light, fluffy bases, run by four Italian friends. Good gluten-free options too.",
    },
    {
      id: "pasta-factory",
      zone: "mackie-mayor",
      name: "The Pasta Factory",
      style: "Italian",
      address: "77 Shudehill, M4 4AN",
      lat: 53.48571,
      lng: -2.23726,
      description: "Fresh pasta made in-house every day by a team from Turin, with inventive fillings and classic sauces.",
    },
    {
      id: "honest-crust",
      zone: "mackie-mayor",
      name: "Honest Crust",
      style: "Pizza",
      address: "Mackie Mayor, 1 Eagle Street, M4 5BU",
      lat: 53.48555,
      lng: -2.23465,
      description: "Wood-fired sourdough pizza from 48-hour dough, with specials built around small producers, in the Mackie Mayor food hall.",
    },
    {
      id: "ciaooo",
      zone: "mackie-mayor",
      name: "Ciaooo",
      style: "Pizza",
      address: "62–64 Swan Street, M4 5JU",
      lat: 53.48608,
      lng: -2.2353,
      description: "A cult-favourite Neapolitan pizzeria famous for its huge crusts and deep-fried lasagne.",
    },
    // City Centre
    {
      id: "salvis",
      zone: "city-centre",
      name: "Salvi's",
      style: "Italian",
      address: "The Corn Exchange, Hanging Ditch, M4 3TR",
      lat: 53.48474,
      lng: -2.24307,
      description: "A family-run Neapolitan kitchen with buffalo mozzarella from its own farm near Naples.",
    },
    {
      id: "riva-blu",
      zone: "city-centre",
      name: "Riva Blu",
      style: "Italian",
      address: "The Corn Exchange, 37 Hanging Ditch, M4 3TR",
      lat: 53.48491,
      lng: -2.24259,
      description: "A glamorous Italian restaurant and bar in the Corn Exchange, known for attentive service.",
    },
    {
      id: "double-zero",
      zone: "city-centre",
      name: "Double Zero",
      style: "Pizza",
      address: "55 Spring Gardens, M2 2BY",
      lat: 53.48023,
      lng: -2.24133,
      description: "Neapolitan-style pizza that's among the city's highest rated, in the heart of the business district.",
    },
    {
      id: "san-carlo-bottega",
      zone: "city-centre",
      name: "San Carlo Bottega",
      style: "Italian",
      address: "Selfridges, 1 Exchange Square, M3 1BD",
      lat: 53.48395,
      lng: -2.24377,
      description: "San Carlo's Milanese-style bar and restaurant on the second floor of Selfridges.",
    },
    // Piccadilly
    {
      id: "rudys-portland-street",
      zone: "piccadilly",
      name: "Rudy's (Portland Street)",
      style: "Pizza",
      address: "30 Portland Street, M1 4GS",
      lat: 53.4792,
      lng: -2.2378,
      description: "Manchester-born Neapolitan pizza: soft, blistered crusts and short, simple menus. Book ahead.",
    },
    {
      id: "bravissimi",
      zone: "piccadilly",
      name: "Bravissimi",
      style: "Italian",
      address: "Piccadilly Station Approach, M1 2GH",
      lat: 53.47877,
      lng: -2.23218,
      description: "A small, friendly spot for traditional Italian food near the station.",
    },
    {
      id: "franco-manca-piccadilly",
      zone: "piccadilly",
      name: "Franco Manca",
      style: "Pizza",
      address: "12–14 Mosley Street, M2 3AG",
      lat: 53.48093,
      lng: -2.23928,
      description: "Sourdough pizza at good prices from the London-born chain, just off Piccadilly Gardens.",
    },
    // Deansgate & St Peter's
    {
      id: "vincenzo",
      zone: "deansgate-st-peters",
      name: "Vincenzo Trattoria",
      style: "Italian",
      address: "34 St Ann Street, M2 7LE",
      lat: 53.48166,
      lng: -2.24505,
      description: "TripAdvisor's top-rated Italian in Manchester: fritto misto, lobster ravioli and classic desserts, tucked between Deansgate and Cross Street.",
    },
    {
      id: "gios",
      zone: "deansgate-st-peters",
      name: "Gio's Ristorante",
      style: "Italian",
      address: "5–7 Lower Mosley Street, M2 3WS",
      lat: 53.47712,
      lng: -2.24422,
      description: "A family-friendly Italian with pizza and pasta, handy for the Bridgewater Hall.",
    },
    {
      id: "don-giovanni",
      zone: "deansgate-st-peters",
      name: "Don Giovanni",
      style: "Italian",
      address: "Oxford Street, M1 5AE",
      lat: 53.47692,
      lng: -2.24349,
      description: "A multi-award-winning Italian that's been going for more than 35 years. The ragù is the one to order.",
    },
    {
      id: "rudys-peter-street",
      zone: "deansgate-st-peters",
      name: "Rudy's (Peter Street)",
      style: "Pizza",
      address: "31 Peter Street, M2 5QJ",
      lat: 53.47818,
      lng: -2.24752,
      description: "Rudy's Neapolitan pizza by St Peter's Square, great before a show.",
    },
    {
      id: "piccolino",
      zone: "deansgate-st-peters",
      name: "Piccolino",
      style: "Italian",
      address: "8 Clarence Street, M2 4DW",
      lat: 53.48,
      lng: -2.24445,
      description: "A lavish flagship with an oyster bar, salumeria and gelato counter alongside classic Italian dishes.",
    },
    {
      id: "italiana-fifty-five",
      zone: "deansgate-st-peters",
      name: "Italiana Fifty Five",
      style: "Italian",
      address: "Great Northern, M3 4EN",
      lat: 53.47761,
      lng: -2.24907,
      description: "A busy Italian in the Great Northern warehouse with big portions of pizza and pasta. The garlic bread gets rave reviews.",
    },
    // Spinningfields
    {
      id: "san-carlo",
      zone: "spinningfields",
      name: "San Carlo",
      style: "Italian",
      address: "40 King Street West, M3 2WY",
      lat: 53.48148,
      lng: -2.24861,
      description: "The glamorous flagship of the Italian group: contemporary classics, seafood and an upmarket crowd.",
    },
    {
      id: "capris",
      zone: "spinningfields",
      name: "Capri's Cucina Italiana",
      style: "Italian",
      address: "118–124 Deansgate, M3 2GQ",
      lat: 53.48143,
      lng: -2.24835,
      description: "A warm, family-run Italian on Deansgate serving pizza and pasta.",
    },
    // Oxford Street
    {
      id: "onda",
      zone: "oxford-street",
      name: "Onda",
      style: "Pasta",
      address: "Circle Square, 3 Symphony Park, M1 7FS",
      lat: 53.47314,
      lng: -2.23901,
      description: "A pop-up turned restaurant: fresh pasta made in the dining room by a Michelin-trained chef, and a famous tiramisu scooped from a drawer.",
    },
    {
      id: "giorgios",
      zone: "oxford-street",
      name: "Giorgio's",
      style: "Italian",
      address: "131–133 Portland Street, M1 4PY",
      lat: 53.47618,
      lng: -2.24208,
      description: "A long-running, traditional Italian restaurant with pizza and pasta near Oxford Street.",
    },
  ],
};

export function restaurantsFor(cityId: string, cuisineId: string): FoodStepRestaurant[] {
  return RESTAURANTS[`${cityId}/${cuisineId}`] ?? [];
}
