/** Restaurants on FoodStep's maps, per city and cuisine. Only Manchester's
 * Mexican so far, as the pattern to copy for the rest.
 *
 * Mexican: checked in October 2026 against TripAdvisor's Mexican list, Manchester's
 * Finest (March 2026), The Manc (June 2026) and That's Up (March 2026), and
 * kept to places with 2026 evidence that they're open (closed ones like
 * El Taquero and Liquor & Burn left out). City centre only, so they all sit
 * in a zone (foodStepZones.ts); at most 6 per zone. Positions and addresses
 * are from OpenStreetMap where it has the restaurant, otherwise the
 * restaurant's published address; the Arndale and Kampus ones are placed by
 * hand inside their building. Descriptions are our own. No ratings yet:
 * TripAdvisor's and Google's can only be shown through their licensed APIs.
 *
 * Italian: picked the same way in October 2026, mostly from TripAdvisor's
 * Italian list (city-centre ones), plus Manchester's Finest and other 2026
 * guides for Purezza, Ciaooo, Honest Crust, Onda and Sicilian NQ.
 *
 * Tapas, UK Gastro, Curry and Street Food: picked the same way in October
 * 2026 from TripAdvisor's Indian ranking, 2026 Sunday-roast, tapas and
 * food-hall guides, and current listings; closed ones (Tast Català,
 * December 2025) and ones without 2026 evidence left out. Curry includes
 * the Curry Mile, which has its own zone. Kampus and Albert Square Chop
 * House are placed by hand.
 *
 * Oxford: picked the same way in October 2026 from TripAdvisor's Oxford
 * Mexican and Italian rankings, 2026 restaurant and pub guides and current
 * listings. The Eagle & Child (closed for renovation), the Vaults & Garden
 * (given notice to close) and pubs with no 2026 evidence are left out.
 * Turl Street Kitchen and Benito's Hat are placed by hand.
 *
 * Buenos Aires: its own six cuisines, picked in October 2026 from 2026
 * guides and rankings (World's 101 Best Steak Restaurants 2026, TripAdvisor,
 * Time Out, Mercado de San Telmo guides) and current listings. The market's
 * stalls are placed by hand inside its block.
 *
 * Buenos Aires' Vegan, Gluten-Friendly, Up & Coming and Student-Friendly
 * lists (October 2026) come from Time Out's 2025 and 2026 openings lists,
 * Time Out's sin-TACC guide, 2026 vegan round-ups (TripAdvisor, the Herald,
 * the Michelin Guide) and 2026 pizzeria and bodegón guides. Student-Friendly
 * means cheap and filling, not student discounts, which none of them
 * advertise. Prices are only given where a source says. Each restaurant's
 * zone comes from its position.
 *
 * Then bulked up (October 2026) from TripAdvisor's current Buenos Aires
 * lists (ice cream, empanadas, steakhouses, seafood, bakeries), HappyCow's
 * 2026 vegan ranking, 2026 milanesa and bodegón guides and Time Out's 2025
 * and 2026 openings: each one listed now, and placed where OpenStreetMap
 * has it or at its published address. Up to 15 per cuisine per zone. */

export interface FoodStepRestaurant {
  id: string;
  name: string;
  /** Its neighbourhood: an id from foodStepZones.ts. */
  zone: string;
  /** Shown under the name, e.g. "Mexican" or "Mexican & Japanese". */
  style: string;
  address: string;
  lat: number;
  lng: number;
  description: string;
  /** "$" cheap to "$$$" special-occasion, where a source says. */
  priceRange?: "$" | "$$" | "$$$";
  /** From a licensed source, with its name for the credit line. */
  rating?: { score: number; outOf: number; source: string };
}

const RESTAURANTS: Record<string, FoodStepRestaurant[]> = {
  "manchester/mexican": [
    // Northern Quarter
    {
      id: "birria-brothers",
      zone: "northern-quarter",
      name: "Birria Brothers",
      style: "Mexican",
      address: "Koffee Pot, 84–86 Oldham Street, M4 1LE",
      lat: 53.48414,
      lng: -2.23325,
      description: "Takes over the Koffee Pot from 4pm every day: fried birria tacos with spiced consommé, plus birria ramen. A pop-up that once drew four-hour queues.",
    },
    {
      id: "boogalu",
      zone: "northern-quarter",
      name: "Boogalú",
      style: "Mexican & Latin",
      address: "12 Tariff Street, M1 2FF",
      lat: 53.48125,
      lng: -2.23211,
      description: "A rum and tequila bar with a taqueria: tacos, nachos and grilled prawns, and a lively bottomless brunch at weekends.",
    },
    {
      id: "el-jefe-birria",
      zone: "northern-quarter",
      name: "El Jefe Birria",
      style: "Mexican",
      address: "MALA, 8 Dale Street, M1 1JA",
      lat: 53.48201,
      lng: -2.23498,
      description: "Messy, many-napkin birria quesadillas stuffed with slow-braised meat, stretchy cheese and properly spicy salsa.",
    },
    // Mackie Mayor & Smithfield
    {
      id: "picos-tacos",
      zone: "mackie-mayor",
      name: "Pico's Tacos",
      style: "Mexican",
      address: "Mackie Mayor, 1 Eagle Street, M4 5BU",
      lat: 53.48549,
      lng: -2.23486,
      description: "A taco counter in the Mackie Mayor food hall, pressing its own corn tortillas, with creative fillings, loaded nachos and margaritas.",
    },
    // City Centre
    {
      id: "panchos-burritos",
      zone: "city-centre",
      name: "Pancho's Burritos",
      style: "Mexican",
      address: "Arndale Food Market, 49 High Street, M4 3AH",
      lat: 53.4834,
      lng: -2.2393,
      description: "A market stall making burritos, tacos and enchiladas from family recipes since 2009. Cheap, quick and much loved.",
    },
    {
      id: "barburrito-arndale",
      zone: "city-centre",
      name: "Barburrito (Arndale)",
      style: "Mexican",
      address: "Manchester Arndale, M4 3AQ",
      lat: 53.4838,
      lng: -2.2414,
      description: "The Manchester-born burrito chain's big Arndale branch: quick, filling burritos and bowls built to order.",
    },
    {
      id: "tortilla-arndale",
      zone: "city-centre",
      name: "Tortilla (Arndale)",
      style: "Mexican",
      address: "Manchester Arndale, M4 3AQ",
      lat: 53.483,
      lng: -2.2407,
      description: "Fast-casual burritos, tacos and nachos you build yourself, handy for a shopping break.",
    },
    {
      id: "taco-bell-market-street",
      zone: "city-centre",
      name: "Taco Bell",
      style: "Tex-Mex",
      address: "32 Market Street, M2 1NP",
      lat: 53.48248,
      lng: -2.24315,
      description: "The American fast-food chain's crunchy tacos, burritos and quesadillas, open late.",
    },
    {
      id: "sandinista",
      zone: "city-centre",
      name: "Sandinista",
      style: "Mexican & Latin",
      address: "2 Old Bank Street, M2 7PF",
      lat: 53.48215,
      lng: -2.24491,
      description: "A late-night dive bar off St Ann's Square serving tacos and Latin street food with tequila cocktails.",
    },
    // Piccadilly
    {
      id: "don-tacos",
      zone: "piccadilly",
      name: "Don Tacos",
      style: "Mexican",
      address: "Unit E3, One Piccadilly Gardens, M1 1RG",
      lat: 53.48018,
      lng: -2.23641,
      description: "Says it brought the birria taco to the UK. Come for slow-cooked birria tacos with consommé for dunking, and cheesy quesadillas.",
    },
    {
      id: "barburrito-piccadilly",
      zone: "piccadilly",
      name: "Barburrito (Piccadilly Gardens)",
      style: "Mexican",
      address: "One Piccadilly Gardens, M1 1RG",
      lat: 53.48055,
      lng: -2.23675,
      description: "Where Barburrito started in 2005: build-your-own burritos, bowls and tacos, fast.",
    },
    {
      id: "zambrero-piccadilly",
      zone: "piccadilly",
      name: "Zambrero (Piccadilly)",
      style: "Mexican",
      address: "7–9 Piccadilly, M1 1LZ",
      lat: 53.48177,
      lng: -2.23781,
      description: "An Australian chain doing casual counter-service burritos, tacos and quesadillas.",
    },
    {
      id: "tortilla-piccadilly",
      zone: "piccadilly",
      name: "Tortilla (Piccadilly Station)",
      style: "Mexican",
      address: "Piccadilly Station Approach, M1 2GH",
      lat: 53.47756,
      lng: -2.23107,
      description: "Burritos and tacos to go, right by the station: good for a bite before a train.",
    },
    // The Village
    {
      id: "madre",
      zone: "the-village",
      name: "Madre",
      style: "Mexican",
      address: "Minshull House, 47 Chorlton Street, M1 3FY",
      lat: 53.47737,
      lng: -2.23542,
      description: "A modern Mexican kitchen and cocktail bar: antojitos, oysters, the grill and creative tacos. Crispy pork belly is a favourite.",
    },
    {
      id: "salon-madre",
      zone: "the-village",
      name: "Salón Madre",
      style: "Mexican",
      address: "49 Chorlton Street, Kampus, M1 3FY",
      lat: 53.47758,
      lng: -2.23515,
      description: "Madre's laid-back sibling: a tequila bar and pool hall with Mexican street food, tucked into Kampus.",
    },
    // Deansgate & St Peter's
    {
      id: "peter-street-kitchen",
      zone: "deansgate-st-peters",
      name: "Peter Street Kitchen",
      style: "Mexican & Japanese",
      address: "Free Trade Hall, Peter Street, M2 5GP",
      lat: 53.4779,
      lng: -2.2473,
      description: "An upmarket restaurant in the historic Free Trade Hall, pairing Mexican and Japanese cooking.",
    },
    {
      id: "las-iguanas",
      zone: "deansgate-st-peters",
      name: "Las Iguanas",
      style: "Latin American",
      address: "84 Deansgate, M3 2ER",
      lat: 53.48247,
      lng: -2.24713,
      description: "A lively Latin American chain with Mexican favourites like sizzling fajitas, and a long cocktail list.",
    },
    {
      id: "zambrero-cross-street",
      zone: "deansgate-st-peters",
      name: "Zambrero (Cross Street)",
      style: "Mexican",
      address: "59 Cross Street, M2 4JW",
      lat: 53.48028,
      lng: -2.24497,
      description: "Zambrero's second city-centre counter: quick burritos, bowls and quesadillas near the Town Hall.",
    },
    {
      id: "revolucion-de-cuba",
      zone: "deansgate-st-peters",
      name: "Revolución de Cuba",
      style: "Cuban & Latin",
      address: "11 Peter Street, M2 5QR",
      lat: 53.47832,
      lng: -2.24895,
      description: "A big, noisy rum bar with live music and Latin plates, including burritos, tacos and loaded nachos.",
    },
    // Spinningfields
    {
      id: "ocasa",
      zone: "spinningfields",
      name: "OCASA",
      style: "Mexican",
      address: "1 The Avenue, Spinningfields, M3 3AP",
      lat: 53.4802,
      lng: -2.2502,
      description: "A Tulum-inspired Mexican restaurant and tequila bar, with modern takes on Mexico City street food.",
    },
    // Oxford Street
    {
      id: "listo-burrito",
      zone: "oxford-street",
      name: "Listo Burrito",
      style: "Mexican",
      address: "91–93 Oxford Street, M1 6ET",
      lat: 53.47534,
      lng: -2.24152,
      description: "Quick, build-your-own burritos and bowls, popular for being filling and good value.",
    },
    {
      id: "tortilla-oxford-street",
      zone: "oxford-street",
      name: "Tortilla (Oxford Street)",
      style: "Mexican",
      address: "50 Oxford Street, M1 5EJ",
      lat: 53.476,
      lng: -2.24215,
      description: "Build-your-own burritos, tacos and nachos on the way between St Peter's Square and the universities.",
    },
    {
      id: "casa-mexica",
      zone: "oxford-street",
      name: "Casa Mexica",
      style: "Tex-Mex",
      address: "Chester Street, M1 5QS",
      lat: 53.47242,
      lng: -2.2402,
      description: "A colourful, casual spot for burritos and Tex-Mex classics, with bright murals on the walls.",
    },
  ],
  "manchester/italian": [
    // Northern Quarter
    {
      id: "purezza",
      zone: "northern-quarter",
      name: "Purezza",
      style: "Vegan Italian",
      address: "75–77 High Street, M4 1FS",
      lat: 53.48445,
      lng: -2.23762,
      description: "The UK's original plant-based pizzeria: sourdough pizzas with vegan cheeses made in-house, in a big Northern Quarter space.",
    },
    {
      id: "sicilian-nq",
      zone: "northern-quarter",
      name: "Sicilian NQ",
      style: "Sicilian",
      address: "14 Turner Street, M4 1DZ",
      lat: 53.48382,
      lng: -2.23773,
      description: "A small, family-style Sicilian bistro known for its arancini, cannoli and tiramisu.",
    },
    // Mackie Mayor & Smithfield
    {
      id: "noi-quattro",
      zone: "mackie-mayor",
      name: "Noi Quattro",
      style: "Pizza",
      address: "120 High Street, M4 1HQ",
      lat: 53.48507,
      lng: -2.23543,
      description: "Naples-style pizza with light, fluffy bases, run by four Italian friends. Good gluten-free options too.",
    },
    {
      id: "pasta-factory",
      zone: "mackie-mayor",
      name: "The Pasta Factory",
      style: "Italian",
      address: "77 Shudehill, M4 4AN",
      lat: 53.48571,
      lng: -2.23726,
      description: "Fresh pasta made in-house every day by a team from Turin, with inventive fillings and classic sauces.",
    },
    {
      id: "honest-crust",
      zone: "mackie-mayor",
      name: "Honest Crust",
      style: "Pizza",
      address: "Mackie Mayor, 1 Eagle Street, M4 5BU",
      lat: 53.48555,
      lng: -2.23465,
      description: "Wood-fired sourdough pizza from 48-hour dough, with specials built around small producers, in the Mackie Mayor food hall.",
    },
    {
      id: "ciaooo",
      zone: "mackie-mayor",
      name: "Ciaooo",
      style: "Pizza",
      address: "62–64 Swan Street, M4 5JU",
      lat: 53.48608,
      lng: -2.2353,
      description: "A cult-favourite Neapolitan pizzeria famous for its huge crusts and deep-fried lasagne.",
    },
    // City Centre
    {
      id: "salvis",
      zone: "city-centre",
      name: "Salvi's",
      style: "Italian",
      address: "The Corn Exchange, Hanging Ditch, M4 3TR",
      lat: 53.48474,
      lng: -2.24307,
      description: "A family-run Neapolitan kitchen with buffalo mozzarella from its own farm near Naples.",
    },
    {
      id: "riva-blu",
      zone: "city-centre",
      name: "Riva Blu",
      style: "Italian",
      address: "The Corn Exchange, 37 Hanging Ditch, M4 3TR",
      lat: 53.48491,
      lng: -2.24259,
      description: "A glamorous Italian restaurant and bar in the Corn Exchange, known for attentive service.",
    },
    {
      id: "double-zero",
      zone: "city-centre",
      name: "Double Zero",
      style: "Pizza",
      address: "55 Spring Gardens, M2 2BY",
      lat: 53.48023,
      lng: -2.24133,
      description: "Neapolitan-style pizza that's among the city's highest rated, in the heart of the business district.",
    },
    {
      id: "san-carlo-bottega",
      zone: "city-centre",
      name: "San Carlo Bottega",
      style: "Italian",
      address: "Selfridges, 1 Exchange Square, M3 1BD",
      lat: 53.48395,
      lng: -2.24377,
      description: "San Carlo's Milanese-style bar and restaurant on the second floor of Selfridges.",
    },
    // Piccadilly
    {
      id: "rudys-portland-street",
      zone: "piccadilly",
      name: "Rudy's (Portland Street)",
      style: "Pizza",
      address: "30 Portland Street, M1 4GS",
      lat: 53.4792,
      lng: -2.2378,
      description: "Manchester-born Neapolitan pizza: soft, blistered crusts and short, simple menus. Book ahead.",
    },
    {
      id: "bravissimi",
      zone: "piccadilly",
      name: "Bravissimi",
      style: "Italian",
      address: "Piccadilly Station Approach, M1 2GH",
      lat: 53.47877,
      lng: -2.23218,
      description: "A small, friendly spot for traditional Italian food near the station.",
    },
    {
      id: "franco-manca-piccadilly",
      zone: "piccadilly",
      name: "Franco Manca",
      style: "Pizza",
      address: "12–14 Mosley Street, M2 3AG",
      lat: 53.48093,
      lng: -2.23928,
      description: "Sourdough pizza at good prices from the London-born chain, just off Piccadilly Gardens.",
    },
    // Deansgate & St Peter's
    {
      id: "vincenzo",
      zone: "deansgate-st-peters",
      name: "Vincenzo Trattoria",
      style: "Italian",
      address: "34 St Ann Street, M2 7LE",
      lat: 53.48166,
      lng: -2.24505,
      description: "TripAdvisor's top-rated Italian in Manchester: fritto misto, lobster ravioli and classic desserts, tucked between Deansgate and Cross Street.",
    },
    {
      id: "gios",
      zone: "deansgate-st-peters",
      name: "Gio's Ristorante",
      style: "Italian",
      address: "5–7 Lower Mosley Street, M2 3WS",
      lat: 53.47712,
      lng: -2.24422,
      description: "A family-friendly Italian with pizza and pasta, handy for the Bridgewater Hall.",
    },
    {
      id: "don-giovanni",
      zone: "deansgate-st-peters",
      name: "Don Giovanni",
      style: "Italian",
      address: "Oxford Street, M1 5AE",
      lat: 53.47692,
      lng: -2.24349,
      description: "A multi-award-winning Italian that's been going for more than 35 years. The ragù is the one to order.",
    },
    {
      id: "rudys-peter-street",
      zone: "deansgate-st-peters",
      name: "Rudy's (Peter Street)",
      style: "Pizza",
      address: "31 Peter Street, M2 5QJ",
      lat: 53.47818,
      lng: -2.24752,
      description: "Rudy's Neapolitan pizza by St Peter's Square, great before a show.",
    },
    {
      id: "piccolino",
      zone: "deansgate-st-peters",
      name: "Piccolino",
      style: "Italian",
      address: "8 Clarence Street, M2 4DW",
      lat: 53.48,
      lng: -2.24445,
      description: "A lavish flagship with an oyster bar, salumeria and gelato counter alongside classic Italian dishes.",
    },
    {
      id: "italiana-fifty-five",
      zone: "deansgate-st-peters",
      name: "Italiana Fifty Five",
      style: "Italian",
      address: "Great Northern, M3 4EN",
      lat: 53.47761,
      lng: -2.24907,
      description: "A busy Italian in the Great Northern warehouse with big portions of pizza and pasta. The garlic bread gets rave reviews.",
    },
    // Spinningfields
    {
      id: "san-carlo",
      zone: "spinningfields",
      name: "San Carlo",
      style: "Italian",
      address: "40 King Street West, M3 2WY",
      lat: 53.48148,
      lng: -2.24861,
      description: "The glamorous flagship of the Italian group: contemporary classics, seafood and an upmarket crowd.",
    },
    {
      id: "capris",
      zone: "spinningfields",
      name: "Capri's Cucina Italiana",
      style: "Italian",
      address: "118–124 Deansgate, M3 2GQ",
      lat: 53.48143,
      lng: -2.24835,
      description: "A warm, family-run Italian on Deansgate serving pizza and pasta.",
    },
    // Oxford Street
    {
      id: "onda",
      zone: "oxford-street",
      name: "Onda",
      style: "Pasta",
      address: "Circle Square, 3 Symphony Park, M1 7FS",
      lat: 53.47314,
      lng: -2.23901,
      description: "A pop-up turned restaurant: fresh pasta made in the dining room by a Michelin-trained chef, and a famous tiramisu scooped from a drawer.",
    },
    {
      id: "giorgios",
      zone: "oxford-street",
      name: "Giorgio's",
      style: "Italian",
      address: "131–133 Portland Street, M1 4PY",
      lat: 53.47618,
      lng: -2.24208,
      description: "A long-running, traditional Italian restaurant with pizza and pasta near Oxford Street.",
    },
  ],
  "manchester/tapas": [
    {
      id: "el-gato-negro",
      zone: "deansgate-st-peters",
      name: "El Gato Negro",
      style: "Spanish",
      address: "52 King Street, M2 4LY",
      lat: 53.48112,
      lng: -2.24575,
      description: "Award-winning Spanish small plates across three floors, with a Michelin Bib Gourmand seven years running. Try the chargrilled octopus.",
    },
    {
      id: "evuna-nq",
      zone: "northern-quarter",
      name: "Evuna (Northern Quarter)",
      style: "Spanish",
      address: "79 Thomas Street, M4 1LQ",
      lat: 53.48344,
      lng: -2.23537,
      description: "A Spanish wine merchant's tapas bar on the corner of Thomas Street, with small plates from all over Spain.",
    },
    {
      id: "maricarmen-nq",
      zone: "northern-quarter",
      name: "Maricarmen",
      style: "Spanish",
      address: "104 High Street, M4 1HQ",
      lat: 53.48462,
      lng: -2.23668,
      description: "Walk-in tapas the Spanish way: trays of freshly made plates circulate the room and you pick what you fancy, at £3 a plate on El Tableo nights.",
    },
    {
      id: "evuna-deansgate",
      zone: "deansgate-st-peters",
      name: "Evuna (Deansgate)",
      style: "Spanish",
      address: "279 Deansgate, M3 4EW",
      lat: 53.47625,
      lng: -2.25055,
      description: "Evuna's original Deansgate restaurant: regional Spanish tapas and a big list of Spanish wines.",
    },
    {
      id: "el-rincon-de-rafa",
      zone: "deansgate-st-peters",
      name: "El Rincón de Rafa",
      style: "Spanish",
      address: "Longworth Street, M3 4BQ",
      lat: 53.478,
      lng: -2.25029,
      description: "A family-run, cellar-like tapas bar tucked behind Deansgate, serving cheap, traditional tapas for over 30 years.",
    },
    {
      id: "molly-house",
      zone: "the-village",
      name: "The Molly House",
      style: "Spanish & Latin",
      address: "26 Richmond Street, M1 3NB",
      lat: 53.47732,
      lng: -2.2371,
      description: "A cosy Village pub and tea room with Spanish and Latin American tapas, plenty for vegans, and award-winning beer.",
    },
  ],
  "manchester/uk-gastro": [
    {
      id: "fountain-house",
      zone: "deansgate-st-peters",
      name: "The Fountain House",
      style: "British",
      address: "14 Albert Square, M2 5PF",
      lat: 53.47893,
      lng: -2.24601,
      description: "A grand Gothic building on Albert Square serving classic British food, with a much-praised Sunday roast beef.",
    },
    {
      id: "ten-tib-lane",
      zone: "deansgate-st-peters",
      name: "10 Tib Lane",
      style: "British",
      address: "10 Tib Lane, M2 4JB",
      lat: 53.48044,
      lng: -2.24458,
      description: "A townhouse near the Town Hall with seasonal sharing plates and a Sunday roast of dry-aged sirloin and porchetta.",
    },
    {
      id: "beef-and-pudding",
      zone: "deansgate-st-peters",
      name: "Beef & Pudding",
      style: "British",
      address: "37 Booth Street, M2 4AA",
      lat: 53.47954,
      lng: -2.24216,
      description: "Proper British comfort food: roast beef and Yorkshire puddings, pies and a pork belly roast with black pudding stuffing.",
    },
    {
      id: "sams-chop-house",
      zone: "city-centre",
      name: "Sam's Chop House",
      style: "British",
      address: "19 Chapel Walks, M2 1HN",
      lat: 53.48171,
      lng: -2.24355,
      description: "A Victorian chop house dating from 1872, still serving corned beef hash, steak pudding and Sunday roasts.",
    },
    {
      id: "mr-thomass-chop-house",
      zone: "deansgate-st-peters",
      name: "Mr Thomas's Chop House",
      style: "British",
      address: "52 Cross Street, M2 7AR",
      lat: 53.48133,
      lng: -2.24489,
      description: "Manchester's oldest chop house, from 1867: tiled Victorian rooms and hearty British classics.",
    },
    {
      id: "albert-square-chop-house",
      zone: "deansgate-st-peters",
      name: "Albert Square Chop House",
      style: "British",
      address: "Memorial Hall, Albert Square, M2 5PF",
      lat: 53.4788,
      lng: -2.2448,
      description: "The third of the Victorian chop houses, in a listed hall facing the Town Hall: pub, dining room and roasts.",
    },
    {
      id: "hawksmoor",
      zone: "deansgate-st-peters",
      name: "Hawksmoor",
      style: "British steakhouse",
      address: "184–186 Deansgate, M3 3WB",
      lat: 53.47897,
      lng: -2.24938,
      description: "Steaks and a famous Sunday roast, cooked over charcoal in a Grade II-listed Victorian courthouse.",
    },
    {
      id: "twenty-stories",
      zone: "spinningfields",
      name: "20 Stories",
      style: "Modern British",
      address: "1 Hardman Square, M3 3EB",
      lat: 53.47893,
      lng: -2.25202,
      description: "A rooftop restaurant twenty storeys above Spinningfields, with modern British cooking and big views.",
    },
    {
      id: "gorilla",
      zone: "oxford-street",
      name: "Gorilla",
      style: "British",
      address: "54–56 Whitworth Street West, M1 5WW",
      lat: 53.47419,
      lng: -2.24262,
      description: "A bar and music venue under the railway arches with a roast of dry-aged Lancashire beef on Sundays.",
    },
    {
      id: "the-refuge",
      zone: "oxford-street",
      name: "The Refuge",
      style: "British",
      address: "Kimpton Clocktower, Oxford Street, M60 7HA",
      lat: 53.47433,
      lng: -2.24031,
      description: "Small plates and Sunday roasts in the grand Victorian halls of the old Refuge Assurance building.",
    },
  ],
  "manchester/curry": [
    {
      id: "this-and-that",
      zone: "northern-quarter",
      name: "This & That",
      style: "Indian",
      address: "3 Soap Street, M4 1EW",
      lat: 53.48471,
      lng: -2.23813,
      description: "A legendary Northern Quarter canteen: pick a rice and three from the day's curries, cheap and fast.",
    },
    {
      id: "kabana",
      zone: "northern-quarter",
      name: "Kabana",
      style: "Pakistani",
      address: "51 Back Turner Street, M4 1FP",
      lat: 53.48361,
      lng: -2.23659,
      description: "Family-run since 1982: rice and three from a changing selection of home-style curries, and lamb nihari on Sundays.",
    },
    {
      id: "delhi-house-cafe",
      zone: "city-centre",
      name: "Delhi House Cafe",
      style: "Indian",
      address: "The Corn Exchange, 37 Hanging Ditch, M4 3TR",
      lat: 53.48508,
      lng: -2.24282,
      description: "Old Delhi street food and curries in a colourful café setting in the Corn Exchange.",
    },
    {
      id: "mowgli",
      zone: "city-centre",
      name: "Mowgli Street Food",
      style: "Indian",
      address: "The Corn Exchange, Hanging Ditch, M4 3TR",
      lat: 53.48511,
      lng: -2.24339,
      description: "Indian home cooking and street-food small plates, like yoghurt chat bombs and the house lamb curry.",
    },
    {
      id: "eastzeast",
      zone: "deansgate-st-peters",
      name: "eastZeast",
      style: "Punjabi",
      address: "30 Blackfriars Street, M3 5BQ",
      lat: 53.48389,
      lng: -2.24829,
      description: "A big, long-running Punjabi restaurant with traditional curries and grills.",
    },
    {
      id: "rajdoot",
      zone: "deansgate-st-peters",
      name: "Rajdoot Tandoori",
      style: "Indian",
      address: "18 Albert Square, M2 5PE",
      lat: 53.47889,
      lng: -2.24558,
      description: "A classic, white-tablecloth Indian restaurant on Albert Square, going since the 1960s.",
    },
    {
      id: "ashas",
      zone: "deansgate-st-peters",
      name: "Asha's",
      style: "Indian",
      address: "47 Peter Street, M2 3NG",
      lat: 53.47802,
      lng: -2.24649,
      description: "Contemporary Indian food and cocktails, founded by the legendary singer Asha Bhosle.",
    },
    {
      id: "dishoom",
      zone: "spinningfields",
      name: "Dishoom",
      style: "Indian",
      address: "32 Bridge Street, M3 3BZ",
      lat: 53.48109,
      lng: -2.25019,
      description: "Bombay café cooking, from bacon naan rolls at breakfast to black daal and biryani, in a grand old Masonic hall.",
    },
    {
      id: "bundobust-piccadilly",
      zone: "piccadilly",
      name: "Bundobust",
      style: "Indian",
      address: "61 Piccadilly, M1 2AG",
      lat: 53.4809,
      lng: -2.23458,
      description: "Vegetarian Indian street food and craft beer: okra fries, bhel puri and vada pav.",
    },
    {
      id: "sangam",
      zone: "deansgate-st-peters",
      name: "Sangam",
      style: "Indian",
      address: "100 Portland Street, M1 4GX",
      lat: 53.47719,
      lng: -2.241,
      description: "A big, popular Indian restaurant with a long menu of classic curries and tandoori dishes.",
    },
    {
      id: "arnero",
      zone: "chinatown",
      name: "Arnero",
      style: "Indian",
      address: "25 Sackville Street, M1 3LZ",
      lat: 53.47745,
      lng: -2.23767,
      description: "Modern Indian cooking with a smart, contemporary feel, near the Village.",
    },
    {
      id: "sthan-m1",
      zone: "oxford-street",
      name: "Sthan M1",
      style: "Indian",
      address: "50 Princess Street, M1 6HR",
      lat: 53.47671,
      lng: -2.23947,
      description: "A small, highly rated modern Indian restaurant on Princess Street.",
    },
    {
      id: "mughli",
      zone: "curry-mile",
      name: "Mughli Charcoal Pit",
      style: "Indian & Pakistani",
      address: "28–32 Wilmslow Road, M14 5TQ",
      lat: 53.45585,
      lng: -2.22563,
      description: "Often called the best on the Curry Mile: North Indian and Pakistani cooking from the charcoal pit and clay oven.",
    },
    {
      id: "ziya",
      zone: "curry-mile",
      name: "Ziya Asian Grill",
      style: "Indian & Pakistani",
      address: "65–67 Wilmslow Road, M14 5TB",
      lat: 53.45622,
      lng: -2.22539,
      description: "A smart, modern grill on the Curry Mile with sizzling platters and big sharing curries.",
    },
    {
      id: "shere-khan",
      zone: "curry-mile",
      name: "Shere Khan",
      style: "Indian",
      address: "50–52 Wilmslow Road, M14 5TQ",
      lat: 53.45527,
      lng: -2.22532,
      description: "The Curry Mile's first fully licensed Indian restaurant, open since 1987.",
    },
    {
      id: "mylahore",
      zone: "curry-mile",
      name: "MyLahore",
      style: "Pakistani",
      address: "14–18 Wilmslow Road, M14 5TQ",
      lat: 53.45615,
      lng: -2.22583,
      description: "A bright, modern spot for traditional curries, bhajis and grills, plus burgers and shakes.",
    },
  ],
  "manchester/street-food": [
    {
      id: "mackie-mayor-hall",
      zone: "mackie-mayor",
      name: "Mackie Mayor",
      style: "Food hall",
      address: "1 Eagle Street, M4 5BU",
      lat: 53.48565,
      lng: -2.23505,
      description: "A restored Victorian market hall full of independent counters: pizza, tacos, ramen, burgers and craft beer at long shared tables.",
    },
    {
      id: "arndale-food-market",
      zone: "city-centre",
      name: "Arndale Food Market",
      style: "Food market",
      address: "49 High Street, M4 3AH",
      lat: 53.48381,
      lng: -2.23911,
      description: "A busy indoor market of cheap and cheerful stalls from around the world, right in the Arndale.",
    },
    {
      id: "mowgli-street-food",
      zone: "city-centre",
      name: "Mowgli Street Food",
      style: "Indian street food",
      address: "The Corn Exchange, Hanging Ditch, M4 3TR",
      lat: 53.48511,
      lng: -2.24339,
      description: "Indian home cooking and street-food small plates, like yoghurt chat bombs and tiffin boxes.",
    },
    {
      id: "bundobust-street-food",
      zone: "piccadilly",
      name: "Bundobust",
      style: "Indian street food",
      address: "61 Piccadilly, M1 2AG",
      lat: 53.4809,
      lng: -2.23458,
      description: "Vegetarian Indian street food and craft beer: okra fries, bhel puri and vada pav.",
    },
    {
      id: "kampus",
      zone: "the-village",
      name: "Kampus",
      style: "Food & drink",
      address: "Aytoun Street, M1 3GL",
      lat: 53.47737,
      lng: -2.23422,
      description: "A new canal-side neighbourhood of independent food and drink spots, with gardens to eat in.",
    },
    {
      id: "society",
      zone: "oxford-street",
      name: "Society",
      style: "Food hall",
      address: "100 Barbirolli Square, M2 3BD",
      lat: 53.47583,
      lng: -2.24501,
      description: "A compact basement food hall by the Bridgewater Hall: chaat, burgers, Korean fried chicken and Asian plates.",
    },
    {
      id: "hello-oriental",
      zone: "oxford-street",
      name: "Hello Oriental",
      style: "Asian food hall",
      address: "2 Symphony Park, Circle Square, M1 7FS",
      lat: 53.47264,
      lng: -2.23814,
      description: "An underground Asian food hall and supermarket: ramen, pho, dumplings and Korean street food.",
    },
  ],
  "oxford/mexican": [
    {
      id: "mission-burrito",
      zone: "cornmarket",
      name: "Mission Burrito",
      style: "Mexican",
      address: "8 St Michael's Street, OX1 2DU",
      lat: 51.75354,
      lng: -1.25923,
      description: "Big, quick, build-your-own burritos just off Cornmarket.",
    },
    {
      id: "benitos-hat",
      zone: "westgate",
      name: "Benito's Hat",
      style: "Mexican",
      address: "Westgate Social, Westgate Centre, OX1 1NZ",
      lat: 51.7506,
      lng: -1.26145,
      description: "A Mexican street-food counter in the Westgate food court: burritos, tacos and frozen margaritas, from a Mexican chef's family recipes.",
    },
    {
      id: "bigfoot",
      zone: "cowley-road",
      name: "Bigfoot",
      style: "Mexican-inspired bar",
      address: "98 Cowley Road, OX4 1JE",
      lat: 51.74841,
      lng: -1.23956,
      description: "A laid-back Cowley Road bar with a fairy-lit terrace, tacos and margaritas.",
    },
  ],
  "oxford/italian": [
    {
      id: "bbuona-pinsa-bar",
      zone: "george-street",
      name: "BBuona Pinsa Bar",
      style: "Italian",
      address: "102 Gloucester Green, OX1 2DF",
      lat: 51.7543,
      lng: -1.26128,
      description: "TripAdvisor's top-rated Italian in Oxford: Roman-style pinsa with light, airy crusts and Italian toppings.",
    },
    {
      id: "100-pasta",
      zone: "george-street",
      name: "100% Pasta",
      style: "Pasta",
      address: "100–101 Gloucester Green, OX1 2DF",
      lat: 51.75431,
      lng: -1.26158,
      description: "Fresh pasta made every day, served quickly and simply, on Gloucester Green.",
    },
    {
      id: "ginos",
      zone: "george-street",
      name: "Gino's",
      style: "Italian",
      address: "94 Gloucester Green, OX1 2BU",
      lat: 51.75439,
      lng: -1.26228,
      description: "A long-running, family-style spaghetti house by the bus station.",
    },
    {
      id: "white-rabbit",
      zone: "george-street",
      name: "The White Rabbit",
      style: "Pub pizza",
      address: "21 Friars Entry, OX1 2BY",
      lat: 51.75449,
      lng: -1.2607,
      description: "A lively little pub serving well-loved wood-fired pizzas.",
    },
    {
      id: "sartorellis",
      zone: "covered-market",
      name: "Sartorelli's",
      style: "Pizza",
      address: "24–25 Avenue 1, Covered Market, OX1 3DU",
      lat: 51.75278,
      lng: -1.25696,
      description: "A tiny, top-rated pizza counter inside the Covered Market.",
    },
    {
      id: "il-corno",
      zone: "covered-market",
      name: "Il Corno",
      style: "Italian",
      address: "40–41 Avenue 2, Covered Market, OX1 3DX",
      lat: 51.75262,
      lng: -1.25687,
      description: "A panuozzo bar in the Covered Market: Neapolitan pizza-dough sandwiches, baked to order.",
    },
    {
      id: "franco-manca",
      zone: "cornmarket",
      name: "Franco Manca",
      style: "Pizza",
      address: "12 George Street, OX1 2AF",
      lat: 51.75399,
      lng: -1.25933,
      description: "Sourdough pizza at good prices from the London-born chain.",
    },
    {
      id: "bella-italia",
      zone: "cornmarket",
      name: "Bella Italia",
      style: "Italian",
      address: "14–16 George Street, OX1 2AF",
      lat: 51.7539,
      lng: -1.25964,
      description: "A dependable family Italian with pizza and pasta, just off Cornmarket.",
    },
    {
      id: "italiamo",
      zone: "high-street",
      name: "ItaliAmo Trattoria",
      style: "Italian",
      address: "21 Broad Street, OX1 3AS",
      lat: 51.75413,
      lng: -1.257,
      description: "A small, friendly trattoria on Broad Street with home-style pasta.",
    },
    {
      id: "branca",
      zone: "jericho",
      name: "Branca",
      style: "Italian",
      address: "110–111 Walton Street, OX2 6AJ",
      lat: 51.76073,
      lng: -1.26674,
      description: "Jericho's go-to Italian for pizza, pasta and weekend brunch.",
    },
    {
      id: "mamma-mia-jericho",
      zone: "jericho",
      name: "Mamma Mia (Jericho)",
      style: "Pizza",
      address: "102 Walton Street, OX2 6EB",
      lat: 51.76108,
      lng: -1.26732,
      description: "A cheerful neighbourhood pizzeria on Walton Street.",
    },
    {
      id: "mamma-mia-summertown",
      zone: "summertown",
      name: "Mamma Mia (Summertown)",
      style: "Pizza",
      address: "9 South Parade, OX2 7JL",
      lat: 51.77844,
      lng: -1.2671,
      description: "Summertown's popular family pizzeria and trattoria.",
    },
    {
      id: "la-cucina",
      zone: "cowley-road",
      name: "La Cucina",
      style: "Italian",
      address: "39–40 St Clement's Street, OX4 1AG",
      lat: 51.75034,
      lng: -1.24199,
      description: "A busy, warm Italian on St Clement's, known for big plates of pasta.",
    },
    {
      id: "cafe-coco",
      zone: "cowley-road",
      name: "Café Coco",
      style: "Italian & Mediterranean",
      address: "23 Cowley Road, OX4 1HP",
      lat: 51.74959,
      lng: -1.24294,
      description: "A Cowley Road favourite for brunch, pizzas and Mediterranean plates.",
    },
    {
      id: "mario",
      zone: "cowley-road",
      name: "Pizzeria Trattoria Mario",
      style: "Italian",
      address: "103 Cowley Road, OX4 1HU",
      lat: 51.74837,
      lng: -1.23831,
      description: "A traditional pizzeria and trattoria on Cowley Road.",
    },
    {
      id: "fresco",
      zone: "cowley-road",
      name: "Fresco",
      style: "Italian",
      address: "218 Cowley Road, OX4 1UQ",
      lat: 51.74651,
      lng: -1.23345,
      description: "A small, highly rated Italian further up Cowley Road.",
    },
    {
      id: "la-smorfia",
      zone: "cowley-road",
      name: "La Smorfia",
      style: "Pizza",
      address: "247 Cowley Road, OX4 1XG",
      lat: 51.74532,
      lng: -1.23005,
      description: "Neapolitan pizza with a top TripAdvisor rating, at the far end of Cowley Road.",
    },
  ],
  "oxford/tapas": [
    {
      id: "arbequina",
      zone: "cowley-road",
      name: "Arbequina",
      style: "Spanish",
      address: "72–74 Cowley Road, OX4 1JB",
      lat: 51.74885,
      lng: -1.24082,
      description: "One of Oxford's best restaurants: bustling Spanish tapas, and a tortilla that's a local benchmark.",
    },
    {
      id: "kazbar",
      zone: "cowley-road",
      name: "Kazbar",
      style: "Spanish & Moroccan",
      address: "25–27 Cowley Road, OX4 1HP",
      lat: 51.74952,
      lng: -1.24274,
      description: "A colourful tapas and cocktail bar with Spanish and North African sharing plates.",
    },
    {
      id: "la-taberna",
      zone: "high-street",
      name: "La Taberna",
      style: "Spanish",
      address: "135a High Street, OX1 4DN",
      lat: 51.75188,
      lng: -1.25689,
      description: "A cosy Spanish tapas bar on the High Street.",
    },
    {
      id: "al-andalus",
      zone: "jericho",
      name: "Al-Andalus",
      style: "Spanish",
      address: "10 Little Clarendon Street, OX1 2HP",
      lat: 51.75862,
      lng: -1.2619,
      description: "Traditional tapas and flamenco nights on Little Clarendon Street.",
    },
  ],
  "oxford/uk-gastro": [
    {
      id: "magdalen-arms",
      zone: "cowley-road",
      name: "The Magdalen Arms",
      style: "British",
      address: "243 Iffley Road, OX4 1SJ",
      lat: 51.74128,
      lng: -1.23668,
      description: "One of Oxford's most serious dining pubs: twice-baked soufflé, slow-cooked lamb to share and great roasts.",
    },
    {
      id: "the-anchor",
      zone: "summertown",
      name: "The Anchor",
      style: "British",
      address: "2 Hayfield Road, OX2 6TT",
      lat: 51.76769,
      lng: -1.26904,
      description: "A North Oxford gastropub with one of the city's biggest garden terraces and Sunday roasts.",
    },
    {
      id: "the-castle",
      zone: "westgate",
      name: "The Castle",
      style: "British",
      address: "24 Paradise Street, OX1 1LD",
      lat: 51.7507,
      lng: -1.26196,
      description: "A historic pub by the castle, known for its generous Sunday roast, pies and hotpot.",
    },
    {
      id: "cosy-club",
      zone: "cornmarket",
      name: "Cosy Club",
      style: "British",
      address: "20 Cornmarket Street, OX1 3EY",
      lat: 51.75316,
      lng: -1.25829,
      description: "Comfort food and cocktails in a grand, eclectic first-floor room on Cornmarket.",
    },
    {
      id: "pieminister",
      zone: "covered-market",
      name: "Pieminister",
      style: "British",
      address: "Avenue 2, Covered Market, OX1 3DX",
      lat: 51.75285,
      lng: -1.25679,
      description: "Proper pies with mash, peas and gravy in the Covered Market.",
    },
  ],
  "oxford/pub-food": [
    {
      id: "turf-tavern",
      zone: "high-street",
      name: "Turf Tavern",
      style: "Pub",
      address: "4–5 Bath Place, OX1 3SU",
      lat: 51.75469,
      lng: -1.25277,
      description: "A medieval alehouse hidden down narrow alleys, with pub classics like rabbit and cider pie.",
    },
    {
      id: "the-bear",
      zone: "high-street",
      name: "The Bear Inn",
      style: "Pub",
      address: "6 Alfred Street, OX1 4EH",
      lat: 51.75155,
      lng: -1.2557,
      description: "Serving Oxford since 1242: a tiny, low-ceilinged pub famous for its collection of ties.",
    },
    {
      id: "kings-arms",
      zone: "high-street",
      name: "King's Arms",
      style: "Pub",
      address: "40 Holywell Street, OX1 3SP",
      lat: 51.75508,
      lng: -1.25432,
      description: "A big, busy university pub at the corner of Broad Street, with classic pub food.",
    },
    {
      id: "lamb-and-flag",
      zone: "cornmarket",
      name: "Lamb & Flag",
      style: "Pub",
      address: "12 St Giles', OX1 3JS",
      lat: 51.7574,
      lng: -1.25929,
      description: "An academic old pub owned by St John's College, with well-kept ales and simple food.",
    },
    {
      id: "old-bookbinders",
      zone: "jericho",
      name: "The Old Bookbinders",
      style: "Pub",
      address: "17–18 Victor Street, OX2 6BT",
      lat: 51.75856,
      lng: -1.26975,
      description: "A quirky Jericho pub from 1869, crammed with curios and known for its French bistro menu.",
    },
    {
      id: "rickety-press",
      zone: "jericho",
      name: "The Rickety Press",
      style: "Pub",
      address: "67 Cranham Street, OX2 6BT",
      lat: 51.75988,
      lng: -1.26829,
      description: "A Jericho backstreet pub with some of Oxford's best wood-fired pizzas.",
    },
    {
      id: "rusty-bicycle",
      zone: "cowley-road",
      name: "The Rusty Bicycle",
      style: "Pub",
      address: "28 Magdalen Road, OX4 1RB",
      lat: 51.74296,
      lng: -1.23427,
      description: "A friendly East Oxford local doing woodfired pizzas and juicy burgers.",
    },
  ],
  "oxford/seasonal-british": [
    {
      id: "turl-street-kitchen",
      zone: "high-street",
      name: "Turl Street Kitchen",
      style: "Seasonal British",
      address: "16–17 Turl Street, OX1 3DH",
      lat: 51.75385,
      lng: -1.2562,
      description: "A not-for-profit kitchen supporting a student charity, cooking a daily-changing seasonal menu from local produce.",
    },
    {
      id: "ashmolean-rooftop",
      zone: "cornmarket",
      name: "Ashmolean Rooftop Restaurant",
      style: "Modern British",
      address: "Ashmolean Museum, Beaumont Street, OX1 2PH",
      lat: 51.75564,
      lng: -1.25991,
      description: "Seasonal British lunches and afternoon tea on the museum's roof terrace, above the spires.",
    },
    {
      id: "no1-ship-street",
      zone: "cornmarket",
      name: "No.1 Ship Street",
      style: "Modern British",
      address: "1 Ship Street, OX1 3DA",
      lat: 51.7537,
      lng: -1.258,
      description: "A smart, modern restaurant with seasonal British and European cooking.",
    },
    {
      id: "cherwell-boathouse",
      zone: "summertown",
      name: "Cherwell Boathouse",
      style: "Modern British",
      address: "50 Bardwell Road, OX2 6ST",
      lat: 51.76963,
      lng: -1.25377,
      description: "A punt station since 1904 with a riverside dining room: modern English cooking and a celebrated wine list.",
    },
  ],
  "oxford/vintage-dining": [
    {
      id: "grand-cafe",
      zone: "high-street",
      name: "The Grand Café",
      style: "Café",
      address: "84 High Street, OX1 4BG",
      lat: 51.75248,
      lng: -1.25058,
      description: "On the site of England's first coffee house, from 1650: gilded and mirrored, for afternoon tea and cocktails.",
    },
    {
      id: "quod",
      zone: "high-street",
      name: "Quod",
      style: "Brasserie",
      address: "92–94 High Street, OX1 4BJ",
      lat: 51.75249,
      lng: -1.25329,
      description: "A grand brasserie in an old High Street banking hall, a long-time Oxford favourite.",
    },
    {
      id: "the-ivy",
      zone: "high-street",
      name: "The Ivy Oxford Brasserie",
      style: "Brasserie",
      address: "120–121 High Street, OX1 4DF",
      lat: 51.75214,
      lng: -1.25567,
      description: "Art deco glamour and all-day British brasserie classics on the High.",
    },
    {
      id: "the-alice",
      zone: "cornmarket",
      name: "The Alice",
      style: "British",
      address: "The Randolph, Beaumont Street, OX1 2LN",
      lat: 51.75507,
      lng: -1.2595,
      description: "The grand Victorian dining room of the Randolph hotel, opposite the Ashmolean.",
    },
    {
      id: "chez-mal",
      zone: "westgate",
      name: "Chez Mal",
      style: "Brasserie",
      address: "Malmaison, 3 New Road, OX1 1AY",
      lat: 51.75158,
      lng: -1.26247,
      description: "A brasserie inside Oxford's old castle prison, now the Malmaison hotel.",
    },
    {
      id: "parsonage-grill",
      zone: "jericho",
      name: "Parsonage Grill",
      style: "British",
      address: "Old Parsonage, 1 Banbury Road, OX2 6NN",
      lat: 51.75944,
      lng: -1.2605,
      description: "A clubby, art-filled grill in a 17th-century parsonage, now a boutique hotel.",
    },
    {
      id: "browns",
      zone: "jericho",
      name: "Browns",
      style: "Brasserie",
      address: "5–11 Woodstock Road, OX2 6HA",
      lat: 51.75903,
      lng: -1.2612,
      description: "An Oxford institution since the 1970s: a big, buzzy brasserie of British classics.",
    },
    {
      id: "gees",
      zone: "jericho",
      name: "Gee's",
      style: "Mediterranean",
      address: "61A Banbury Road, OX2 6PE",
      lat: 51.7643,
      lng: -1.2612,
      description: "A Victorian glass conservatory turned restaurant, serving since 1989, with Mediterranean-inspired cooking.",
    },
  ],
  "buenos-aires/empanadas": [
    {
      id: "la-cocina",
      zone: "recoleta",
      name: "La Cocina",
      style: "Empanadas",
      address: "Av. Pueyrredón 1508, Barrio Norte",
      lat: -34.59311,
      lng: -58.40192,
      description: "Since 1977: Catamarca-style empanadas, some of the country's best, in a small, cosy spot.",
    },
    {
      id: "el-sanjuanino",
      zone: "recoleta",
      name: "El Sanjuanino",
      style: "Empanadas",
      address: "Posadas 1515, Recoleta",
      lat: -34.58726,
      lng: -58.38738,
      description: "A traditional tavern near the cemetery, famous for juicy, spiced salteña empanadas.",
    },
    {
      id: "cumen-cumen",
      zone: "recoleta",
      name: "Cümen-Cümen",
      style: "Empanadas",
      address: "Recoleta",
      lat: -34.58882,
      lng: -58.39153,
      description: "A popular empanada house with a long list of fillings, baked and fried.",
    },
    {
      id: "1810",
      zone: "palermo",
      name: "1810 Cocina Regional",
      style: "Empanadas",
      address: "Julián Álvarez 1998, Palermo",
      lat: -34.5894,
      lng: -58.4194,
      description: "Northern Argentine cooking: Tucumán-style empanadas, locro and humita.",
    },
    {
      id: "el-hornero-mercado",
      zone: "mercado-san-telmo",
      name: "Empanadas at the Mercado",
      style: "Empanadas",
      address: "Mercado de San Telmo, Defensa 963",
      lat: -34.6193,
      lng: -58.3728,
      description: "A market counter for empanadas, tamales and locro, with beer on tap.",
    },
    {
      id: "la-aguada",
      zone: "recoleta",
      name: "La Aguada",
      style: "Northern Argentine",
      address: "Billinghurst, Barrio Norte",
      lat: -34.58905,
      lng: -58.4092,
      description: "Highly rated cooking from Argentina's north-west, with excellent empanadas.",
    },
    {
      id: "cumana",
      zone: "recoleta",
      name: "Cumaná",
      style: "Empanadas",
      address: "Rodríguez Peña 1149, Barrio Norte",
      lat: -34.59553,
      lng: -58.39183,
      description: "A busy, colourful spot for clay-oven empanadas, locro and cazuelas.",
    },
    {
      id: "la-morada",
      zone: "centro",
      name: "La Morada",
      style: "Empanadas",
      address: "Hipólito Yrigoyen 778, Monserrat",
      lat: -34.60943,
      lng: -58.37737,
      description: "A downtown favourite for empanadas and northern Argentine dishes.",
    },
    {
      id: "la-querencia",
      zone: "recoleta",
      name: "La Querencia",
      style: "Regional Argentine",
      address: "Junín, Recoleta",
      lat: -34.59287,
      lng: -58.3972,
      description: "Regional Argentine food, with empanadas and locro, in Recoleta.",
    },
    {
      id: "mengano",
      zone: "palermo",
      name: "Mengano",
      style: "Modern bodegón",
      address: "José Antonio Cabrera 5172, Palermo",
      lat: -34.58897,
      lng: -58.43375,
      description: "A modern bodegón famous for its spicy fried beef empanada.",
    },
    {
      id: "el-banco-rojo",
      zone: "mercado-san-telmo",
      name: "El Banco Rojo",
      style: "Empanadas & snacks",
      address: "Bolívar 914, San Telmo",
      lat: -34.61869,
      lng: -58.37292,
      description: "A cheap and cheerful San Telmo counter for empanadas, sandwiches and burgers, by the market.",
    },
  ],
  "buenos-aires/milanesa": [
    {
      id: "el-preferido",
      zone: "palermo",
      name: "El Preferido de Palermo",
      style: "Bodegón",
      address: "Jorge Luis Borges 2108, Palermo",
      lat: -34.58544,
      lng: -58.42538,
      description: "A restored corner bodegón with a monster of a milanesa napolitana.",
    },
    {
      id: "club-de-la-milanesa",
      zone: "palermo",
      name: "El Club de la Milanesa",
      style: "Milanesa",
      address: "Gurruchaga, Palermo Soho",
      lat: -34.58789,
      lng: -58.42717,
      description: "A restaurant all about milanesas, with dozens of toppings and sizes to share.",
    },
    {
      id: "santos-manjares",
      zone: "centro",
      name: "Santos Manjares",
      style: "Milanesa",
      address: "Paraguay 938, Retiro",
      lat: -34.59771,
      lng: -58.38031,
      description: "A small, much-loved downtown spot for milanesas and grilled meats.",
    },
    {
      id: "manolo",
      zone: "san-telmo",
      name: "Manolo",
      style: "Bodegón",
      address: "Bolívar 1299, San Telmo",
      lat: -34.62309,
      lng: -58.37282,
      description: "A classic San Telmo bodegón, known for its milanesas and generous plates.",
    },
    {
      id: "el-obrero",
      zone: "la-boca",
      name: "El Obrero",
      style: "Bodegón",
      address: "Agustín R. Caffarena 64, La Boca",
      lat: -34.62968,
      lng: -58.35683,
      description: "A La Boca bodegón since 1954, full of signed football shirts: giant milanesas and homemade ravioli at fair prices.",
      priceRange: "$$",
    },
    {
      id: "don-ignacio",
      zone: "almagro",
      name: "Don Ignacio",
      style: "Milanesa",
      address: "Av. Rivadavia 3439, Almagro",
      lat: -34.61065,
      lng: -58.41502,
      description: "35 kinds of milanesa, hand-breaded with fresh breadcrumbs: often called the city's best.",
    },
    {
      id: "el-progreso",
      zone: "centro",
      name: "El Progreso",
      style: "Bodegón",
      address: "Club del Progreso, Sarmiento 1334, San Nicolás",
      lat: -34.60532,
      lng: -58.38546,
      description: "A historic bodegón inside the Club del Progreso, with a milanesa big enough for four.",
    },
    {
      id: "lo-de-jaime",
      zone: "palermo",
      name: "Lo de Jaime",
      style: "Parrilla & milanesas",
      address: "Honduras 4518, Palermo",
      lat: -34.59202,
      lng: -58.4254,
      description: "A Palermo parrilla known for its milanesa napolitana.",
    },
    {
      id: "pepito",
      zone: "centro",
      name: "Pepito",
      style: "Bodegón",
      address: "Montevideo 383, San Nicolás",
      lat: -34.60452,
      lng: -58.38931,
      description: "A 75-year-old classic with XL milanesas in several sizes.",
    },
  ],
  "buenos-aires/gelato": [
    {
      id: "cadore",
      zone: "centro",
      name: "Cadore",
      style: "Heladería",
      address: "Av. Corrientes 1695, San Nicolás",
      lat: -34.60417,
      lng: -58.39065,
      description: "Founded in 1957 by an Italian family, and named among the world's best ice cream shops. Try the dulce de leche.",
    },
    {
      id: "rapa-nui",
      zone: "recoleta",
      name: "Rapa Nui",
      style: "Heladería",
      address: "Arenales 2302, Barrio Norte",
      lat: -34.59418,
      lng: -58.39963,
      description: "Patagonian chocolatiers turned helado makers: rich chocolate and berry flavours.",
    },
    {
      id: "luccianos",
      zone: "palermo",
      name: "Lucciano's",
      style: "Heladería",
      address: "Lafinur, Palermo Botánico",
      lat: -34.57966,
      lng: -58.41372,
      description: "Italian-style gelato that many call the best they've had in Argentina.",
    },
    {
      id: "freddo",
      zone: "recoleta",
      name: "Freddo",
      style: "Heladería",
      address: "Ayacucho 1906, Recoleta",
      lat: -34.58817,
      lng: -58.38997,
      description: "Buenos Aires' best-known helado chain; this branch is a short walk from the Recoleta cemetery.",
    },
    {
      id: "tufic",
      zone: "palermo",
      name: "Tufic Helados",
      style: "Heladería",
      address: "Guatemala 4597, Palermo Soho",
      lat: -34.58706,
      lng: -58.4234,
      description: "Artisan helado that regularly makes lists of the city's best.",
    },
    {
      id: "scannapieco",
      zone: "villa-crespo",
      name: "Heladería Scannapieco",
      style: "Heladería",
      address: "Av. Álvarez Thomas 10, Chacarita",
      lat: -34.5832,
      lng: -58.44472,
      description: "An old-school family heladería, a favourite with locals.",
    },
    {
      id: "rapa-nui-retiro",
      zone: "centro",
      name: "Rapa Nui (Retiro)",
      style: "Heladería",
      address: "Av. Santa Fe 772, Retiro",
      lat: -34.59519,
      lng: -58.37786,
      description: "Rapa Nui's downtown shop for Patagonian chocolate and rich helado.",
    },
    {
      id: "buffala",
      zone: "recoleta",
      name: "Heladería Búffala",
      style: "Heladería",
      address: "Av. Pueyrredón 2100, Recoleta",
      lat: -34.58788,
      lng: -58.39826,
      description: "A popular, well-rated heladería in Recoleta.",
    },
    {
      id: "aversa",
      zone: "palermo",
      name: "Aversa Helados",
      style: "Heladería",
      address: "Av. del Libertador 2828, Palermo",
      lat: -34.57791,
      lng: -58.40935,
      description: "A small, highly rated artisan heladería on Avenida del Libertador.",
    },
    {
      id: "valence",
      zone: "recoleta",
      name: "Valence",
      style: "Heladería & café",
      address: "Juncal, Barrio Norte",
      lat: -34.59407,
      lng: -58.392,
      description: "Good helado and desserts in a modern, clean café.",
    },
    {
      id: "etzio",
      zone: "centro",
      name: "Etzio Heladería",
      style: "Heladería",
      address: "Montevideo, San Nicolás",
      lat: -34.60469,
      lng: -58.38945,
      description: "A small heladería almost hidden on Montevideo street, with a loyal following.",
    },
    {
      id: "nuestro-secreto",
      zone: "centro",
      name: "Nuestro Secreto",
      style: "Heladería",
      address: "Four Seasons, Posadas 1086, Retiro",
      lat: -34.59062,
      lng: -58.38276,
      description: "The Four Seasons' own heladería, one of TripAdvisor's top three in the city.",
    },
    {
      id: "alchemy",
      zone: "palermo",
      name: "Alchemy",
      style: "Heladería",
      address: "Humboldt 1923, Palermo Hollywood",
      lat: -34.58326,
      lng: -58.43346,
      description: "Creative, chef-made helado in Palermo Hollywood.",
    },
  ],
  "buenos-aires/parrilla": [
    {
      id: "don-julio",
      zone: "palermo",
      name: "Don Julio",
      style: "Parrilla",
      address: "Guatemala 4691, Palermo Soho",
      lat: -34.58629,
      lng: -58.42427,
      description: "The city's most famous parrilla, three times the world's best steak restaurant. Book well ahead.",
    },
    {
      id: "la-cabrera",
      zone: "palermo",
      name: "La Cabrera",
      style: "Parrilla",
      address: "José Antonio Cabrera 5099, Palermo",
      lat: -34.58937,
      lng: -58.43288,
      description: "Huge steaks with a parade of little side dishes; a Palermo favourite for a night out.",
    },
    {
      id: "fogon-asado",
      zone: "palermo",
      name: "Fogón Asado",
      style: "Parrilla",
      address: "Uriarte 1423, Palermo",
      lat: -34.5885,
      lng: -58.43362,
      description: "An asado tasting menu cooked in front of you; 22nd in the world's best steak restaurants for 2026.",
    },
    {
      id: "el-desnivel",
      zone: "san-telmo",
      name: "El Desnivel",
      style: "Parrilla",
      address: "Defensa 855, San Telmo",
      lat: -34.61786,
      lng: -58.37174,
      description: "A loud, no-frills San Telmo parrilla: big portions, low prices, lots of tradition.",
    },
    {
      id: "la-brigada",
      zone: "san-telmo",
      name: "La Brigada",
      style: "Parrilla",
      address: "Estados Unidos 465, San Telmo",
      lat: -34.61844,
      lng: -58.37274,
      description: "A San Telmo institution for over 30 years, with football shirts on the walls and meat cut with a spoon.",
    },
    {
      id: "parrilla-pena",
      zone: "centro",
      name: "Parrilla Peña",
      style: "Parrilla",
      address: "Rodríguez Peña 682, San Nicolás",
      lat: -34.60117,
      lng: -58.3915,
      description: "A great, honest parrilla with even better prices.",
    },
    {
      id: "elena",
      zone: "centro",
      name: "Elena",
      style: "Parrilla",
      address: "Four Seasons, Posadas 1086, Retiro",
      lat: -34.59057,
      lng: -58.38257,
      description: "An elegant hotel steakhouse with dry-aged beef; in the world's top 101 steak restaurants for 2026.",
    },
    {
      id: "happening",
      zone: "puerto-madero",
      name: "Happening",
      style: "Parrilla",
      address: "Puerto Madero",
      lat: -34.60239,
      lng: -58.36688,
      description: "A waterside parrilla on the docks, in the world's top 101 steak restaurants for 2026.",
    },
    {
      id: "la-choripaneria",
      zone: "mercado-san-telmo",
      name: "La Choripanería",
      style: "Choripán",
      address: "Mercado de San Telmo, Defensa 963",
      lat: -34.6189,
      lng: -58.3729,
      description: "The market's best choripán: pork or lamb chorizo grilled behind the bar, with different sauces.",
    },
    {
      id: "nro-53",
      zone: "mercado-san-telmo",
      name: "NRO 53",
      style: "Parrilla",
      address: "Mercado de San Telmo, Defensa 963",
      lat: -34.6192,
      lng: -58.3723,
      description: "A market grill where you pick your cut, with seats along the counter and in the central hall.",
    },
    {
      id: "calden-del-soho",
      zone: "palermo",
      name: "Caldén del Soho",
      style: "Parrilla",
      address: "Honduras 4701, Palermo Soho",
      lat: -34.59063,
      lng: -58.42705,
      description: "TripAdvisor's top-rated steakhouse in the city in 2026: a warm, friendly Palermo parrilla.",
    },
    {
      id: "hierro-palermo",
      zone: "palermo",
      name: "Hierro (Palermo)",
      style: "Parrilla",
      address: "Costa Rica 5610, Palermo Hollywood",
      lat: -34.58267,
      lng: -58.43487,
      description: "A modern parrilla from the Hierro team, among the city's best rated.",
    },
    {
      id: "hierro-san-telmo",
      zone: "mercado-san-telmo",
      name: "Hierro (San Telmo)",
      style: "Parrilla",
      address: "Bolívar 970, San Telmo",
      lat: -34.61936,
      lng: -58.37242,
      description: "Hierro's San Telmo parrilla, on Bolívar by the market, one of the best rated in the city.",
    },
    {
      id: "la-dorita",
      zone: "palermo",
      name: "La Dorita",
      style: "Parrilla",
      address: "Humboldt 1892, Palermo Hollywood",
      lat: -34.58341,
      lng: -58.43391,
      description: "A well-loved neighbourhood parrilla, among TripAdvisor's top rated.",
    },
    {
      id: "el-mercado-faena",
      zone: "puerto-madero",
      name: "El Mercado (Faena)",
      style: "Parrilla",
      address: "Faena Hotel, Martha Salotti 445, Puerto Madero",
      lat: -34.61407,
      lng: -58.36173,
      description: "The Faena hotel's restaurant, cooking over fire; among the city's top-rated steakhouses.",
      priceRange: "$$$",
    },
    {
      id: "voro",
      zone: "palermo",
      name: "Parrilla Voro",
      style: "Parrilla",
      address: "José Antonio Cabrera, Palermo",
      lat: -34.58807,
      lng: -58.43463,
      description: "A small Palermo parrilla with top TripAdvisor ratings.",
    },
    {
      id: "el-gran-paraiso",
      zone: "la-boca",
      name: "El Gran Paraíso",
      style: "Parrilla",
      address: "Paseo Garibaldi, La Boca",
      lat: -34.6394,
      lng: -58.36328,
      description: "A La Boca parrilla a few steps from Caminito.",
    },
    {
      id: "revire",
      zone: "centro",
      name: "Revire Brasas Bravas",
      style: "Parrilla",
      address: "Av. Corrientes 1124, San Nicolás",
      lat: -34.60392,
      lng: -58.38259,
      description: "A highly rated parrilla near the Obelisco.",
    },
    {
      id: "cero-5",
      zone: "centro",
      name: "Parrilla Cero 5",
      style: "Parrilla",
      address: "Suipacha 930, Retiro",
      lat: -34.59719,
      lng: -58.37993,
      description: "A small, well-rated downtown parrilla.",
    },
    {
      id: "huacho",
      zone: "centro",
      name: "Huacho",
      style: "Parrilla",
      address: "Esmeralda 1050, Retiro",
      lat: -34.59588,
      lng: -58.37859,
      description: "A small, highly rated parrilla in Retiro.",
    },
    {
      id: "minga",
      zone: "palermo",
      name: "Minga",
      style: "Parrilla",
      address: "Costa Rica, Palermo Soho",
      lat: -34.58926,
      lng: -58.42555,
      description: "A popular Palermo Soho parrilla.",
    },
    {
      id: "aires-criollos",
      zone: "recoleta",
      name: "Aires Criollos",
      style: "Parrilla",
      address: "Av. Santa Fe, Barrio Norte",
      lat: -34.5957,
      lng: -58.39276,
      description: "A traditional parrilla on Avenida Santa Fe.",
    },
    {
      id: "mirasol-puerto",
      zone: "puerto-madero",
      name: "El Mirasol del Puerto",
      style: "Parrilla",
      address: "Av. Alicia Moreau de Justo 202, Puerto Madero",
      lat: -34.60094,
      lng: -58.36727,
      description: "A classic Puerto Madero steakhouse on the docks.",
      priceRange: "$$$",
    },
    {
      id: "las-canas",
      zone: "centro",
      name: "Las Cañas",
      style: "Parrilla",
      address: "Montevideo 350, San Nicolás",
      lat: -34.60492,
      lng: -58.38946,
      description: "A traditional parrilla near Congreso, much liked by visitors.",
    },
    {
      id: "abreboca",
      zone: "villa-crespo",
      name: "Abreboca",
      style: "Neo-pulpería",
      address: "Fraga 541, Chacarita",
      lat: -34.58502,
      lng: -58.45169,
      description: "A neo-pulpería with house-cured charcuterie and an ojo de bife with chimichurri butter.",
    },
  ],
  "buenos-aires/panaderia": [
    {
      id: "boulan",
      zone: "palermo",
      name: "Boûlan",
      style: "Bakery",
      address: "Ugarteche 3045, Palermo Botánico",
      lat: -34.58081,
      lng: -58.41198,
      description: "Often called the best bakery in Buenos Aires, with croissants to die for.",
    },
    {
      id: "domani",
      zone: "palermo",
      name: "Domani",
      style: "Bakery",
      address: "Jerónimo Salguero 3000, Palermo",
      lat: -34.57786,
      lng: -58.40617,
      description: "Regularly named the city's best for medialunas: soft, big and glazed just right.",
    },
    {
      id: "daniel-bakery",
      zone: "palermo",
      name: "Daniel Bakery",
      style: "Bakery",
      address: "Av. Honduras 3714, Palermo",
      lat: -34.59422,
      lng: -58.41494,
      description: "Croissants in unusual flavours; the pistachio cream one is famous.",
    },
    {
      id: "oui-oui",
      zone: "palermo",
      name: "Oui Oui",
      style: "Café & bakery",
      address: "Nicaragua 6099, Palermo Hollywood",
      lat: -34.57755,
      lng: -58.43854,
      description: "A French-leaning café-panadería that helped make brunch a Buenos Aires thing.",
    },
    {
      id: "obrador-de-panes",
      zone: "san-telmo",
      name: "Obrador de Panes",
      style: "Bakery",
      address: "Chile 524, San Telmo",
      lat: -34.61609,
      lng: -58.37351,
      description: "A hidden San Telmo bakery for fresh bread, cakes, cookies and pies.",
    },
    {
      id: "merci",
      zone: "mercado-san-telmo",
      name: "Merci",
      style: "Bakery & pâtisserie",
      address: "Mercado de San Telmo, Defensa 963",
      lat: -34.619,
      lng: -58.3722,
      description: "A panadería and pâtisserie inside the market, with tapas and wine later in the day.",
    },
    {
      id: "las-violetas",
      zone: "almagro",
      name: "Las Violetas",
      style: "Confitería",
      address: "Av. Rivadavia 3899, Almagro",
      lat: -34.61127,
      lng: -58.42091,
      description: "A grand café from 1884, famous for its stained glass and enormous afternoon teas.",
    },
    {
      id: "cocu",
      zone: "palermo",
      name: "Cocu Boulangerie",
      style: "Bakery",
      address: "Malabia, Palermo Soho",
      lat: -34.59128,
      lng: -58.42802,
      description: "A warm, French-style boulangerie at the edge of Palermo Soho: breads, quiches and brioche au chocolat.",
    },
    {
      id: "malvon",
      zone: "villa-crespo",
      name: "Malvón",
      style: "Café & bakery",
      address: "Serrano, Villa Crespo",
      lat: -34.59433,
      lng: -58.43911,
      description: "A popular Villa Crespo café-bakery for brunch and pastries.",
    },
    {
      id: "salvaje",
      zone: "palermo",
      name: "Salvaje Bakery",
      style: "Bakery",
      address: "Dorrego 1829, Palermo",
      lat: -34.58073,
      lng: -58.44212,
      description: "A sourdough bakery and sandwich shop with communal tables.",
    },
    {
      id: "lepi",
      zone: "recoleta",
      name: "L'épi Boulangerie",
      style: "Bakery",
      address: "Montevideo 1567, Recoleta",
      lat: -34.59199,
      lng: -58.3883,
      description: "A French bakery known for its medialunas and breads.",
    },
    {
      id: "atelier-fuerza",
      zone: "palermo",
      name: "Atelier Fuerza",
      style: "Bakery",
      address: "Gral. Lucio N. Mansilla 3801, Palermo",
      lat: -34.58929,
      lng: -58.41698,
      description: "Started as a sourdough bakery; now known for some of the city's best gourmet facturas.",
    },
    {
      id: "le-moulin",
      zone: "recoleta",
      name: "Le Moulin de la Fleur",
      style: "Patisserie",
      address: "Av. Pueyrredón 1824, Recoleta",
      lat: -34.58983,
      lng: -58.40038,
      description: "A French-style patisserie and café in Recoleta.",
    },
    {
      id: "rustica",
      zone: "recoleta",
      name: "Rústica",
      style: "Patisserie",
      address: "Agüero 2284, Recoleta",
      lat: -34.58662,
      lng: -58.40048,
      description: "A pastry shop for cakes and tarts in Recoleta.",
    },
    {
      id: "pertutti",
      zone: "recoleta",
      name: "Pertutti",
      style: "Café & patisserie",
      address: "Av. Santa Fe, Barrio Norte",
      lat: -34.5959,
      lng: -58.39654,
      description: "A classic café-patisserie for cakes and merienda on Avenida Santa Fe.",
    },
    {
      id: "negro-hollywood",
      zone: "palermo",
      name: "Negro Hollywood",
      style: "Café & pastries",
      address: "Arévalo 2051, Palermo Hollywood",
      lat: -34.57808,
      lng: -58.43704,
      description: "New in 2026: specialty coffee and artisan pastries, with vinyl on the turntable.",
    },
    {
      id: "siembra",
      zone: "palermo",
      name: "Siembra",
      style: "Café & bakery",
      address: "Humboldt 1906, Palermo Hollywood",
      lat: -34.58328,
      lng: -58.43369,
      description: "New in 2026: a neighbourhood café for specialty coffee, bagels and brunch.",
    },
  ],
  "buenos-aires/fish": [
    {
      id: "la-pescadorita",
      zone: "palermo",
      name: "La Pescadorita",
      style: "Seafood",
      address: "Humboldt 1905, Palermo Hollywood",
      lat: -34.58339,
      lng: -58.43353,
      description: "One of the city's best-loved seafood restaurants, with thousands of glowing reviews.",
    },
    {
      id: "crizia",
      zone: "palermo",
      name: "Crizia",
      style: "Seafood",
      address: "Gorriti 5143, Palermo Soho",
      lat: -34.58841,
      lng: -58.43255,
      description: "Stylish seafood with platters, an oyster bar and a smart crowd.",
    },
    {
      id: "la-mar",
      zone: "palermo",
      name: "La Mar",
      style: "Peruvian seafood",
      address: "Arévalo 2024, Palermo Hollywood",
      lat: -34.57826,
      lng: -58.43756,
      description: "Peruvian cebichería: ceviches, tiraditos and fresh fish.",
    },
    {
      id: "oviedo",
      zone: "recoleta",
      name: "Oviedo",
      style: "Spanish seafood",
      address: "Beruti 2602, Barrio Norte",
      lat: -34.59212,
      lng: -58.40296,
      description: "A Spanish restaurant going for over 30 years, known for its fish and seafood.",
    },
    {
      id: "tancat",
      zone: "centro",
      name: "Tancat",
      style: "Spanish seafood",
      address: "Paraguay 645, Retiro",
      lat: -34.59746,
      lng: -58.37605,
      description: "A busy Spanish tavern with seafood and Mediterranean dishes, packed at lunchtime.",
    },
    {
      id: "sorrento",
      zone: "puerto-madero",
      name: "Sorrento",
      style: "Seafood",
      address: "Puerto Madero",
      lat: -34.6029,
      lng: -58.36681,
      description: "Mediterranean fish and seafood by the water in Puerto Madero.",
    },
    {
      id: "fervor",
      zone: "recoleta",
      name: "Fervor",
      style: "Grill & seafood",
      address: "Posadas 1519, Recoleta",
      lat: -34.58734,
      lng: -58.38726,
      description: "A smart Recoleta restaurant known for both its steaks and its fish and seafood.",
      priceRange: "$$$",
    },
    {
      id: "osaka-madero",
      zone: "puerto-madero",
      name: "Osaka (Puerto Madero)",
      style: "Nikkei",
      address: "Juana Manso, Puerto Madero",
      lat: -34.6111,
      lng: -58.36249,
      description: "Peruvian-Japanese Nikkei cooking by the docks: ceviches, tiraditos and sushi.",
    },
    {
      id: "chan-chan",
      zone: "centro",
      name: "Chan Chan",
      style: "Peruvian",
      address: "Hipólito Yrigoyen 1390, Monserrat",
      lat: -34.61,
      lng: -58.38588,
      description: "A cheerful, good-value Peruvian spot near Congreso for ceviche and seafood.",
    },
    {
      id: "la-conga",
      zone: "almagro",
      name: "La Conga",
      style: "Peruvian",
      address: "La Rioja 39, Once",
      lat: -34.61091,
      lng: -58.40901,
      description: "A much-loved Peruvian restaurant in Once for ceviches and seafood.",
    },
    {
      id: "damblee",
      zone: "almagro",
      name: "Dambleé",
      style: "Seafood",
      address: "Sánchez de Bustamante, Almagro",
      lat: -34.61059,
      lng: -58.41459,
      description: "A Mediterranean-style seafood restaurant in Almagro.",
    },
    {
      id: "puerto-cristal",
      zone: "puerto-madero",
      name: "Puerto Cristal",
      style: "Seafood",
      address: "Av. Alicia Moreau de Justo 1082, Puerto Madero",
      lat: -34.60991,
      lng: -58.36606,
      description: "A long-running Puerto Madero restaurant for fish and seafood by the water.",
    },
    {
      id: "centro-asturiano",
      zone: "centro",
      name: "Centro Asturiano",
      style: "Spanish seafood",
      address: "Solís 475, Monserrat",
      lat: -34.61445,
      lng: -58.39051,
      description: "The Asturian club's restaurant, cooking Spanish-style fish and seafood.",
    },
    {
      id: "centro-vasco",
      zone: "centro",
      name: "Centro Vasco Francés",
      style: "Basque seafood",
      address: "Moreno 1370, Monserrat",
      lat: -34.61228,
      lng: -58.3857,
      description: "The Basque club's dining room, known for its fish and seafood.",
    },
    {
      id: "dora",
      zone: "centro",
      name: "Dora",
      style: "Seafood",
      address: "Av. Leandro N. Alem, Retiro",
      lat: -34.59585,
      lng: -58.37273,
      description: "An old-school downtown institution for big plates of seafood and Spanish dishes.",
    },
    {
      id: "palacio-espanol",
      zone: "centro",
      name: "Palacio Español",
      style: "Spanish seafood",
      address: "Club Español, Bernardo de Irigoyen 172, Monserrat",
      lat: -34.61036,
      lng: -58.38043,
      description: "Spanish seafood in the grand rooms of the Club Español.",
    },
    {
      id: "plaza-mayor",
      zone: "centro",
      name: "Plaza Mayor",
      style: "Spanish seafood",
      address: "Venezuela, Monserrat",
      lat: -34.61447,
      lng: -58.38585,
      description: "A big, busy Spanish restaurant for paella and seafood.",
    },
  ],
  "buenos-aires/vegan": [
    {
      id: "sacro",
      zone: "palermo",
      name: "Sacro",
      style: "Vegan",
      address: "Costa Rica 6038, Palermo Hollywood",
      lat: -34.57902,
      lng: -58.43938,
      description: "One of the city's best restaurants, vegan or not: stylish tapas-style plates of plants and mushrooms. The kimchi dumplings are a must.",
    },
    {
      id: "artemisia",
      zone: "palermo",
      name: "Artemisia",
      style: "Vegan",
      address: "Costa Rica 5893, Palermo Hollywood",
      lat: -34.58027,
      lng: -58.4375,
      description: "Upscale plant-based cooking, from polenta lasagne to lentil kibbeh, with a little shop attached.",
    },
    {
      id: "buenos-aires-verde",
      zone: "palermo",
      name: "Buenos Aires Verde",
      style: "Vegan",
      address: "Gorriti 5657, Palermo Hollywood",
      lat: -34.58439,
      lng: -58.43774,
      description: "One of the city's best-known all-vegan spots: woks, raw food, cakes and sourdough.",
    },
    {
      id: "sampa",
      zone: "villa-crespo",
      name: "Sampa",
      style: "Vegan parrilla",
      address: "Av. Raúl Scalabrini Ortiz 769, Villa Crespo",
      lat: -34.59664,
      lng: -58.43361,
      description: "Billed as the city's best vegan parrilla: grilled oyster mushrooms and keppe stuffed with potato and portobello.",
    },
    {
      id: "gioia",
      zone: "recoleta",
      name: "Gioia Cocina Botánica",
      style: "Vegetarian & vegan",
      address: "Posadas 1350, Recoleta",
      lat: -34.58851,
      lng: -58.38553,
      description: "In the Michelin Guide: vegetarian, mostly vegan cooking with an Italian botanical twist.",
      priceRange: "$$$",
    },
    {
      id: "la-reverde",
      zone: "centro",
      name: "La Reverde",
      style: "Vegan parrilla",
      address: "Montevideo 40, Congreso",
      lat: -34.60859,
      lng: -58.38931,
      description: "Argentina's asado reinvented: grilled seitan, plant-based chorizos, empanadas and all the parrilla sides.",
    },
    {
      id: "donnet",
      zone: "villa-crespo",
      name: "Donnet",
      style: "Mushroom-based",
      address: "Av. Jorge Newbery 4081, Chacarita",
      lat: -34.58825,
      lng: -58.45085,
      description: "Argentina's first mushroom restaurant, with porteño soul: try the oyster-mushroom matambrito.",
    },
    {
      id: "mudra",
      zone: "almagro",
      name: "Mudrá",
      style: "Vegan",
      address: "Av. Córdoba 3942, Almagro",
      lat: -34.59783,
      lng: -58.42229,
      description: "A chic, ocean-themed vegan spot for plant-based nikkei sushi, burritos and burgers.",
    },
    {
      id: "veganius",
      zone: "palermo",
      name: "Veganius",
      style: "Vegan deli",
      address: "Bonpland 2444, Palermo Hollywood",
      lat: -34.57733,
      lng: -58.43062,
      description: "A vegan deli and food shop since 2014.",
    },
    {
      id: "guille-veggie",
      zone: "almagro",
      name: "Guille Veggie",
      style: "Vegan Peruvian",
      address: "Humahuaca 4101, Almagro",
      lat: -34.60165,
      lng: -58.42252,
      description: "Traditional Peruvian cooking, made entirely plant-based.",
    },
    {
      id: "let-it-v",
      zone: "palermo",
      name: "Let it V",
      style: "Vegan",
      address: "Costa Rica 5865, Palermo Hollywood",
      lat: -34.58053,
      lng: -58.4372,
      description: "Vegan fusion with seasonal organic ingredients, and fully gluten-free too.",
    },
    {
      id: "naturaleza-sabia",
      zone: "centro",
      name: "Naturaleza Sabia",
      style: "Vegetarian & vegan",
      address: "Perú 677, Monserrat",
      lat: -34.6158,
      lng: -58.3746,
      description: "Healthy vegetarian cooking with vegan options: soy milanesas, seitan and a famous bread pudding.",
    },
  ],
  "buenos-aires/gluten-friendly": [
    {
      id: "sintaxis",
      zone: "palermo",
      name: "Sintaxis",
      style: "100% gluten-free",
      address: "Nicaragua 4849, Palermo",
      lat: -34.58628,
      lng: -58.42744,
      description: "Argentina's first gluten-free restaurant: pasta, bread and baking, all sin TACC.",
    },
    {
      id: "cucina-paradiso",
      zone: "palermo",
      name: "Cucina Paradiso",
      style: "100% gluten-free Italian",
      address: "Arévalo 1538, Palermo",
      lat: -34.58237,
      lng: -58.44222,
      description: "Latin America's first fully gluten-free Italian restaurant, with homemade pasta.",
    },
    {
      id: "las-flores",
      zone: "palermo",
      name: "Las Flores",
      style: "100% gluten-free bakery",
      address: "Gorriti 5870, Palermo",
      lat: -34.58221,
      lng: -58.44102,
      description: "A restaurant, bakery and patisserie where everything is gluten-free, with a lab working on making it tastier.",
    },
    {
      id: "la-union",
      zone: "palermo",
      name: "La Unión",
      style: "100% gluten-free bakery",
      address: "Cabello 3426, Palermo Botánico",
      lat: -34.58133,
      lng: -58.40902,
      description: "A gluten-free bakery whose breads and medialunas win over non-coeliacs too.",
    },
    {
      id: "gout",
      zone: "recoleta",
      name: "Goût",
      style: "100% gluten-free patisserie",
      address: "Montevideo 1480, Recoleta",
      lat: -34.59263,
      lng: -58.38935,
      description: "A French-inspired, entirely gluten-free patisserie: mini cakes and pastries.",
    },
    {
      id: "il-mandorla",
      zone: "centro",
      name: "Il Mandorla",
      style: "100% gluten-free",
      address: "Suipacha 749, Centro",
      lat: -34.5996,
      lng: -58.37965,
      description: "A gluten-free smokehouse downtown: sandwiches, empanadas and wood-fired pizza.",
    },
    {
      id: "falafelandia",
      zone: "villa-crespo",
      name: "Falafelandia",
      style: "Gluten-free street food",
      address: "Av. Córdoba 5190, Villa Crespo",
      lat: -34.59042,
      lng: -58.43612,
      description: "A street-food stand for freshly made, gluten-free falafel with vegetables and sauces.",
      priceRange: "$",
    },
    {
      id: "georgies",
      zone: "villa-crespo",
      name: "Georgie's",
      style: "Gluten-free Mexican",
      address: "Charlone 499, Chacarita",
      lat: -34.5829,
      lng: -58.45105,
      description: "Tacos and gorditas on fresh nixtamalised corn tortillas, naturally gluten-free.",
    },
    {
      id: "taccoff",
      zone: "palermo",
      name: "TACCOFF",
      style: "100% gluten-free café",
      address: "Nicaragua 5977, Palermo Hollywood",
      lat: -34.57862,
      lng: -58.43724,
      description: "A fully gluten-free café and patisserie: cakes, bread, pasta and sandwiches.",
    },
    {
      id: "amitie",
      zone: "almagro",
      name: "Amitié",
      style: "Gluten-free café",
      address: "Av. La Plata, Almagro",
      lat: -34.61741,
      lng: -58.42839,
      description: "A gluten-free café, among the city's best-rated sin TACC bakeries.",
    },
  ],
  "buenos-aires/up-and-coming": [
    {
      id: "mambo",
      zone: "villa-crespo",
      name: "Mambo",
      style: "New Argentine",
      address: "Malabia 820, Villa Crespo",
      lat: -34.59591,
      lng: -58.43512,
      description: "Opened 2025 by Santiago Pérez (Casa Cavia, Orilla, Las Flores): contemporary Argentine cooking over real fire.",
    },
    {
      id: "asadero",
      zone: "villa-crespo",
      name: "Asadero",
      style: "Fire cooking",
      address: "Fitz Roy 1041, Chacarita",
      lat: -34.5895,
      lng: -58.44277,
      description: "New in 2026 from the Casa Cavia and Orno team: meat, fish, vegetables and bread, all over embers.",
    },
    {
      id: "silvino",
      zone: "villa-crespo",
      name: "Silvino",
      style: "Bistro",
      address: "Guevara 421, Chacarita",
      lat: -34.58671,
      lng: -58.45058,
      description: "A 2025 seasonal bistro with handmade pasta and reinvented classics.",
    },
    {
      id: "hierro-bodegon",
      zone: "palermo",
      name: "Hierro Bodegón",
      style: "Neo-bodegón",
      address: "Fitz Roy 1722, Palermo Hollywood",
      lat: -34.58388,
      lng: -58.43615,
      description: "Opened 2025 by the Hierro duo: popular Argentine dishes with polished technique.",
    },
    {
      id: "zarautz",
      zone: "palermo",
      name: "Zarautz",
      style: "Seafood",
      address: "Nicaragua 5577, Palermo Hollywood",
      lat: -34.58182,
      lng: -58.43315,
      description: "New in 2026: 30 seats in a century-old house, cooking fish and seafood from Argentina's Atlantic coast.",
    },
    {
      id: "cruzgodoy",
      zone: "palermo",
      name: "CruzGodoy",
      style: "Contemporary",
      address: "Godoy Cruz 1725, Palermo Soho",
      lat: -34.58735,
      lng: -58.43355,
      description: "New in 2026: charred dishes with Asian, Middle Eastern and Latin flavours.",
    },
    {
      id: "avio",
      zone: "palermo",
      name: "Avío",
      style: "Author's cuisine",
      address: "Lavalleja 1521, Palermo",
      lat: -34.59339,
      lng: -58.42329,
      description: "New in 2026 in a converted mechanic's workshop: café by day, global author's cooking by night.",
    },
    {
      id: "barra-chalaca",
      zone: "san-telmo",
      name: "Barra Chalaca",
      style: "Peruvian seafood",
      address: "Av. Caseros 467, San Telmo",
      lat: -34.62656,
      lng: -58.37192,
      description: "New in 2026: Gastón Acurio's casual cantina for Peruvian ceviches and seafood.",
    },
    {
      id: "aldos",
      zone: "san-telmo",
      name: "Aldo's Brasserie Argentina",
      style: "Brasserie",
      address: "Azopardo 780, Bajo Porteño",
      lat: -34.61661,
      lng: -58.36736,
      description: "New in 2026: porteño classics, from grilled meats to historic risottos, in an old corner of the city.",
    },
    {
      id: "allenby",
      zone: "recoleta",
      name: "Allenby",
      style: "Mediterranean",
      address: "Vicente López 2050, Recoleta",
      lat: -34.58927,
      lng: -58.39378,
      description: "New in 2026: Mediterranean and Middle Eastern plates with house-made breads, yoghurt and pickles.",
    },
    {
      id: "presencia",
      zone: "centro",
      name: "Presencia",
      style: "Contemporary",
      address: "Montevideo 1789, Recoleta",
      lat: -34.59007,
      lng: -58.386,
      description: "Opened 2025: a sophisticated contemporary restaurant with a casual café alongside.",
    },
    {
      id: "cantina-recoleta",
      zone: "recoleta",
      name: "Cantina Recoleta",
      style: "Modern cantina",
      address: "Av. Santa Fe 1430, Recoleta",
      lat: -34.5959,
      lng: -58.3877,
      description: "Opened 2025: a modern cantina cooking over wood, with polenta and risotto.",
    },
    {
      id: "trufa",
      zone: "centro",
      name: "Trufa",
      style: "Seasonal",
      address: "Palacio Paz Hotel, Av. Santa Fe 760, Retiro",
      lat: -34.59533,
      lng: -58.37781,
      description: "Opened 2025: seasonal cooking and cocktails in the historic Palacio Paz.",
    },
    {
      id: "kamay",
      zone: "almagro",
      name: "Kamay Casa Gardel",
      style: "Peruvian-Nikkei",
      address: "Carlos Gardel 3131, Abasto",
      lat: -34.6034,
      lng: -58.40936,
      description: "Opened 2025 in tango's old heartland: Peruvian-Nikkei tiraditos and anticuchos.",
    },
    {
      id: "runfla",
      zone: "palermo",
      name: "Runfla",
      style: "Shared plates",
      address: "Báez 315, Las Cañitas",
      lat: -34.57183,
      lng: -58.43134,
      description: "New in 2026: multicultural author's cooking in plates made for sharing.",
    },
    {
      id: "mimo-bar",
      zone: "palermo",
      name: "Mimo Bar",
      style: "Wine & small plates",
      address: "Honduras 5874, Palermo Hollywood",
      lat: -34.58204,
      lng: -58.43912,
      description: "New in 2026: relaxed shared plates and small-producer wines.",
    },
    {
      id: "ambar-recoleta",
      zone: "recoleta",
      name: "Ámbar Recoleta",
      style: "French bistro",
      address: "Junín 1725, Recoleta",
      lat: -34.589,
      lng: -58.39266,
      description: "New in 2026: a French bistro that turns into a bar with live DJs.",
    },
    {
      id: "bulles",
      zone: "recoleta",
      name: "Bulles",
      style: "Champagne bar",
      address: "Guido 1949, Recoleta",
      lat: -34.58872,
      lng: -58.3914,
      description: "New in 2026: the city's first champagne bar, on a 16th floor, with oysters and caviar.",
      priceRange: "$$$",
    },
    {
      id: "koala",
      zone: "palermo",
      name: "Koala",
      style: "Café & kitchen",
      address: "Fray Justo Santa María de Oro 2104, Palermo",
      lat: -34.58326,
      lng: -58.42808,
      description: "Opened 2025: conscious cooking inspired by Australian café culture.",
    },
    {
      id: "bambina",
      zone: "palermo",
      name: "Bambina",
      style: "Pizza & gelato",
      address: "Cabello 3486, Palermo Chico",
      lat: -34.58117,
      lng: -58.40955,
      description: "Opened 2025: Neapolitan pizza and artisan ice cream with seasonal ingredients.",
    },
    {
      id: "jotti",
      zone: "palermo",
      name: "Jotti",
      style: "Sandwiches",
      address: "Jorge Luis Borges 1627, Palermo Soho",
      lat: -34.58853,
      lng: -58.42971,
      description: "Opened 2025: gourmet brioche sandwiches, coffee and cocktails.",
    },
    {
      id: "pani-pizza-feroz",
      zone: "palermo",
      name: "Pani Pizza Feroz",
      style: "Pizza",
      address: "Honduras 4999, Palermo Soho",
      lat: -34.58887,
      lng: -58.42971,
      description: "Opened 2025: long-fermented pizza with creative toppings and cocktails.",
    },
    {
      id: "anasagasti",
      zone: "palermo",
      name: "Anasagasti Omakase",
      style: "Omakase",
      address: "Pasaje Anasagasti 2067, Palermo",
      lat: -34.58888,
      lng: -58.41139,
      description: "Opened 2025: an intimate omakase in a 1927 mansion.",
      priceRange: "$$$",
    },
    {
      id: "electrica",
      zone: "palermo",
      name: "Eléctrica (Palermo)",
      style: "Pizza",
      address: "Honduras 5903, Palermo Hollywood",
      lat: -34.58158,
      lng: -58.43944,
      description: "Opened October 2025: Argentine pizza with Neapolitan technique, Brooklyn-style.",
    },
    {
      id: "territorio-aura",
      zone: "palermo",
      name: "Territorio Aura",
      style: "Open-fire cooking",
      address: "Lafinur 3286, Palermo",
      lat: -34.5778,
      lng: -58.41278,
      description: "Opened November 2025: traditional and open-fire cooking in a forest-themed space.",
    },
    {
      id: "orno-palermo",
      zone: "palermo",
      name: "Orno (Palermo Off)",
      style: "Italian-Argentine",
      address: "Beruti 3336, Palermo",
      lat: -34.58724,
      lng: -58.40964,
      description: "Opened 2025: Italian-Argentine cooking, pizza al taglio, and a cantina upstairs.",
    },
    {
      id: "la-dolfina",
      zone: "palermo",
      name: "La Dolfina Polo Café",
      style: "Argentine classics",
      address: "Av. Figueroa Alcorta 3301, Palermo Chico",
      lat: -34.57795,
      lng: -58.40268,
      description: "New in 2026: an all-day café reworking Argentine classics, from the La Dolfina polo team.",
    },
  ],
  "buenos-aires/student-friendly": [
    {
      id: "guerrin",
      zone: "centro",
      name: "Güerrín",
      style: "Pizzería",
      address: "Av. Corrientes 1368, San Nicolás",
      lat: -34.6041,
      lng: -58.38599,
      description: "Since 1932 by the Obelisco: thick, cheesy slices eaten standing at the marble counter, like a local.",
      priceRange: "$",
    },
    {
      id: "el-cuartito",
      zone: "centro",
      name: "El Cuartito",
      style: "Pizzería",
      address: "Talcahuano 937, Centro",
      lat: -34.59782,
      lng: -58.38546,
      description: "A no-frills 'pizza temple' since 1934, with hearty portions and walls of football and boxing photos.",
      priceRange: "$",
    },
    {
      id: "las-cuartetas",
      zone: "centro",
      name: "Las Cuartetas",
      style: "Pizzería",
      address: "Av. Corrientes 838, Microcentro",
      lat: -34.60368,
      lng: -58.37855,
      description: "A classic Corrientes pizzeria where a tango poet wrote his verses; quick, cheap slices.",
      priceRange: "$",
    },
    {
      id: "la-americana",
      zone: "centro",
      name: "La Americana",
      style: "Pizza & empanadas",
      address: "Av. Callao 83, Congreso",
      lat: -34.60811,
      lng: -58.39187,
      description: "The self-styled queen of empanadas, by Congreso: cheap, fast pizza and empanadas.",
      priceRange: "$",
    },
    {
      id: "bellagamba",
      zone: "palermo",
      name: "Bellagamba",
      style: "Bodegón",
      address: "Francisco Acuña de Figueroa 1291",
      lat: -34.59661,
      lng: -58.42142,
      description: "A classic cheap bodegón for big, homely plates at low prices.",
      priceRange: "$",
    },
    {
      id: "el-imperio",
      zone: "villa-crespo",
      name: "El Imperio",
      style: "Pizzería",
      address: "Av. Corrientes 6899, Chacarita",
      lat: -34.58693,
      lng: -58.45486,
      description: "Since 1947 at the end of Avenida Corrientes: a neighbourhood pizza institution.",
      priceRange: "$",
    },
    {
      id: "banchero",
      zone: "la-boca",
      name: "Banchero",
      style: "Pizzería",
      address: "Av. Almirante Brown & Suárez, La Boca",
      lat: -34.63534,
      lng: -58.35851,
      description: "Founded in La Boca in 1932, where fugazza con queso was born.",
      priceRange: "$",
    },
    {
      id: "la-continental",
      zone: "almagro",
      name: "La Continental",
      style: "Pizzería",
      address: "Av. Ángel Gallardo 12, Almagro",
      lat: -34.60235,
      lng: -58.43222,
      description: "A long-running pizzeria chain for cheap pizza and empanadas.",
      priceRange: "$",
    },
  ],
};

export function restaurantsFor(cityId: string, cuisineId: string): FoodStepRestaurant[] {
  return RESTAURANTS[`${cityId}/${cuisineId}`] ?? [];
}
